Sashas
gsbelarus/gdmn-nxt pull request #137
Opened 2023-01-06 17:58 UTC by sashazernin

2023-01-09 14:12 UTC, hirurg-lybitel commented on apps/gdmn-nxt-web/src/main.tsx
> +    if (item.id === url[4] || item.id === url[3]) {
это что ещё за проверка такая url[4]? А если url более длинным будет?

2023-01-09 14:13 UTC, hirurg-lybitel commented on apps/gdmn-nxt-web/src/main.tsx
> +                  dispatch(setActiveMenu(children.id));
Это вообще достижимый код?
У меня так и не получилось до него дойти.
Какую последовательность действий можно сделать, чтобы дошло до сюда?

2023-01-09 14:16 UTC, hirurg-lybitel commented on apps/gdmn-nxt-web/src/main.tsx
> +        } else {
вообще такая вложенность - это антипаттерн, из-за которого код нечитаемым и труднопонимаемым становится.

Обычно пишут:
  if (!<условие>) <return/skip>

  // do something

2023-01-10 05:37 UTC, sashazernin commented on apps/gdmn-nxt-web/src/main.tsx
> +    if (item.id === url[4] || item.id === url[3]) {
ну, теперь более строгий роутинг но на мой взгляд та все более структурированное, а на счет того что url более длинный сомневаюсь что в navbar будет на столько сильная вложенность (раскрывающийся список в раскрывающемся списке)

2023-01-10 05:38 UTC, sashazernin commented on apps/gdmn-nxt-web/src/main.tsx
> +                  dispatch(setActiveMenu(children.id));
до достижимый

2023-01-10 09:18 UTC, hirurg-lybitel commented on apps/gdmn-nxt-web/src/main.tsx
> +    if (item.id === url[4] || item.id === url[3]) {
Твои сомнения - это интересно, конечно, но в голом остатке есть огромная уязвимость: в коде жёсткое условие на длину url, но есть возможность указывать любой url. Кто-то увеличит url, и всё ломается. 

Просто представь, что ты сам впервые зашёл в исходники и увидел этот код. Ты поймёшь, почему именно url[4]?

2023-01-10 09:24 UTC, hirurg-lybitel commented on apps/gdmn-nxt-web/src/main.tsx
> +                  dispatch(setActiveMenu(children.id));
короче понял, это только после перезагрузке должно сработать

2023-01-10 09:37 UTC, gsbelarus commented
```
  const url:string[] = window.location.href.split(/[/]\s*/);
  menuItems.items.map((item, index) =>{
    if (item.id === url[4] || item.id === url[3]) {
      menuItems.items[index].children?.map(childrens => {
        if (childrens.children) {
          if (childrens.id === url[url.length - 2]) {
            childrens.children.map(children => {
              if (children.url === (url[url.length - 3] + '/' + url[url.length - 2] + '/' + url[url.length - 1])) {
                if (children.id !== settings.activeMenuId && settings.activeMenuId !== '') {
                  dispatch(setActiveMenu(children.id));
                }
              }
            });
          }
```

этот код надо переписать. так никто не делает. начнем с того, что вообще невозможно понять что происходит. надо потратить кучу времени. правильный код он еще и читабельный должен быть сам по себе.

во-вторых, если у тебя ссылки на элемент в массиве, то первое что следует сделать -- это проверить длину. у тебя массив точно будет всегда минимум 5 элементов содержать?

для начала, я бы открыл комментарий в коде и словами написал, что надо сделать. может сразу станет видно как это просто и наглядно сделать в коде.

2023-01-10 16:44 UTC, sashazernin commented on apps/gdmn-nxt-web/src/main.tsx
> +    if (item.id === url[4] || item.id === url[3]) {
а как мне тогда лучше сделать? коммент оставить?

2023-01-10 19:27 UTC, hirurg-lybitel requested changes

2023-01-10 19:27 UTC, hirurg-lybitel commented on apps/gdmn-nxt-web/src/main.tsx
> +  }, [settings.activeMenuId]);
для чего эта зависимость?

2023-01-10 19:27 UTC, hirurg-lybitel commented on apps/gdmn-nxt-web/src/main.tsx
> +    }
Ты молодец, что построил такую сложную **рабочую** логику, но это всё не совсем всё стиле js.

Я бы написал что-то вроде такого вместо всего этого `useEffect`, хотя не проверял:

```
  useEffect(() => {
    const flatMenuItems = (items: IMenuItem[]): IMenuItem[] =>
      items
        .map(item =>
          item.type === 'item'
            ? item
            : flatMenuItems(item.children || []))
        .flatMap(el => el);

    const flattedMenuItems = flatMenuItems(menuItems.items);

    const menuId = url.at(-1) || '';
    flattedMenuItems.findIndex(({ id }) => id === menuId) >= 0 && dispatch(setActiveMenu(menuId));
  }, []);
```

2023-01-10 19:27 UTC, hirurg-lybitel commented on apps/gdmn-nxt-web/src/app/layouts/MainLayout/Sidebar/menu-collapse/menu-collapse.tsx
> +    menu.children?.map((item: IMenuItem) => {
Опять-таки, непонятно зачем тут map, если тебе не нужен новый массив. 
Оно как бы не критично, но нужно понимать, что когда и для чего использовать.

2023-01-10 19:27 UTC, hirurg-lybitel commented on apps/gdmn-nxt-web/src/app/layouts/MainLayout/Sidebar/menu-item/menu-item.tsx
> +  if (settings.activeMenuId === item.id) {
Ненужная вложенность условий.
Проще же написать в данном случае (activeMenuId === item.id && isOpen)

2023-01-10 19:27 UTC, hirurg-lybitel commented on apps/gdmn-nxt-web/src/app/layouts/MainLayout/Sidebar/menu-item/menu-item.tsx
> +      open && open();
Ну и вызов функций должен, конечно же, в useEffect происходить

2023-01-10 20:31 UTC, gsbelarus commented
начни с этой строки
```
const url:string[] = window.location.href.split(/[/]\s*/);
```  
у тебя URL и обращаться надо с ним как с УРЛ, а не полагаться на какие-то предположения. УРЛ имеет строго заданную структуру. Если лень самому разбирать, то есть специальный встроенный в браузер объект для парсинга:
```
const url = new URL(relativeOrAbsolute [, absoluteBase]);
```
после него у тебя на руках будет такая структура:
```
interface URL {
  href:     USVString;
  protocol: USVString;
  username: USVString;
  password: USVString;
  host:     USVString;
  hostname: USVString;
  port:     USVString;
  pathname: USVString;
  search:   USVString;
  hash:     USVString;
  readonly origin: USVString;
  readonly searchParams: URLSearchParams;
  toJSON(): USVString;
}
```
от сюда гораздо проще взять путь и с ним разбираться.

2023-01-11 07:10 UTC, sashazernin commented on apps/gdmn-nxt-web/src/main.tsx
> +  }, [settings.activeMenuId]);
да, но изначально проводится инициализация и этот код должен сработать уже после загрузки остального

2023-01-11 07:14 UTC, sashazernin commented on apps/gdmn-nxt-web/src/app/layouts/MainLayout/Sidebar/menu-collapse/menu-collapse.tsx
> +    menu.children?.map((item: IMenuItem) => {
я map использовал для перебора объекта там и index есть и сразу превращает содержимое в удобные переменные

2023-01-11 07:59 UTC, sashazernin commented on apps/gdmn-nxt-web/src/main.tsx
> +    }
да, так лучше было бы сделать, но мешает /employee. если обращается к system/..,  /employee в начале нету

2023-01-11 16:28 UTC, hirurg-lybitel commented on apps/gdmn-nxt-web/src/main.tsx
> +    }
не понял, а зачем тут `employee` обрабатывать?

2023-01-11 17:22 UTC, gsbelarus commented
find более производительный:

https://www.measurethat.net/Benchmarks/Show/4923/0/find-vs-findindex-array-prototype-methods#latest_results_block

2023-01-11 19:31 UTC, sashazernin commented on apps/gdmn-nxt-web/src/main.tsx
> +    }
ну employee часть адреса корорый при это не указал в массива menuItems

2023-01-11 19:47 UTC, hirurg-lybitel commented
> find более производительный:
> 
> https://www.measurethat.net/Benchmarks/Show/4923/0/find-vs-findindex-array-prototype-methods#latest_results_block

Видимо, зависит, как измерять.
У меня вот такие результаты 
![image](https://user-images.githubusercontent.com/11502258/211903033-63f50e7b-1fd2-4f18-a222-2f3c6382b667.png)

В любом случае в данном кейсе это всё мгновения, поэтому можно поставить во главу угла читаемость.

2023-01-11 19:59 UTC, gsbelarus commented
скорее всего some внутри себя вызывает find. именно по этому он медленнее.

2023-01-11 20:03 UTC, sashazernin commented on apps/gdmn-nxt-web/src/main.tsx
> +    }
я придумал как можно сделать

2023-01-16 13:34 UTC, hirurg-lybitel approved these changes

2023-01-16 13:34 UTC, merged