Deals creating clients
gsbelarus/gdmn-nxt pull request #195
Opened 2023-03-14 09:55 UTC by sashazernin

Сделки. Создание клиента #182

2023-03-24 16:00 UTC, hirurg-lybitel requested changes

2023-03-24 16:00 UTC, hirurg-lybitel commented on apps/gdmn-nxt-web/src/app/components/Charts/chart-column/chart-column.tsx
А какое отношение к указанной задаче имеет этот код по графикам?

2023-03-24 16:00 UTC, hirurg-lybitel commented on apps/gdmn-nxt-web/src/app/components/Kanban/kanban-edit-card/components/customer-select.tsx
> -    editingCustomer
с этим кодом что не так?

2023-03-24 16:00 UTC, hirurg-lybitel commented on yarn.lock
тут что=то поменялось? зачем?

2023-03-24 16:00 UTC, hirurg-lybitel commented on apps/gdmn-nxt-web/src/app/layouts/MainLayout/Header/profile/profile.tsx
какое отношение этот файл имеет к решаемой задаче?

2023-03-27 10:57 UTC, sashazernin commented on apps/gdmn-nxt-web/src/app/components/Kanban/kanban-edit-card/components/customer-select.tsx
> -    editingCustomer
да в целом ничего просто тернарку заменил на обычный иф элс, мне кажется так привычнее что ли

2023-03-27 11:22 UTC, sashazernin commented on yarn.lock
да у меня танцы с бубном были библиотека не ставилась

2023-03-28 12:28 UTC, merged