Group users
gsbelarus/gdmn-nxt pull request #198
Opened 2023-03-15 11:35 UTC by sashazernin

2023-03-24 16:27 UTC, hirurg-lybitel commented
это какая задача?
непонятно, что проверять
@sashazernin

2023-03-24 17:25 UTC, hirurg-lybitel requested changes

2023-03-27 10:53 UTC, sashazernin commented
> Аэто какая задача? Непонятно, что проверять. @sashazernin

Группы пользователей. Поиск пользователя по ФИО #180

2023-03-28 12:30 UTC, hirurg-lybitel approved these changes

2023-03-28 12:30 UTC, merged