Permissions
gsbelarus/gdmn-nxt pull request #230
Opened 2023-04-21 17:54 UTC by sashazernin

2023-04-27 16:20 UTC, hirurg-lybitel requested changes

2023-04-27 16:29 UTC, merged

2023-04-28 02:38 UTC, sashazernin commented on apps/gdmn-nxt-server/src/app/controllers/permissions.ts
> -          DELETE FROM USR$CRM_PERMISSIONS_UG_LINES WHERE CURRENT OF curUserGroup;
я это перенес в отдельную функцию потому что удаление понадобилась в другом месте (Чтобы код не дублировать)

2023-04-28 02:38 UTC, sashazernin commented on apps/gdmn-nxt-server/src/app/controllers/permissions.ts
> +  ).map((id:any)=> id.USR$USERKEY)
да тут косяк

2023-04-28 08:53 UTC, hirurg-lybitel commented on apps/gdmn-nxt-server/src/app/controllers/permissions.ts
> -          DELETE FROM USR$CRM_PERMISSIONS_UG_LINES WHERE CURRENT OF curUserGroup;
в какую?