fix: opening list of menu items when one of the list item is active
gsbelarus/gdmn-nxt pull request #268
Opened 2023-05-18 16:39 UTC by sashazernin

#259

2023-05-19 09:41 UTC, hirurg-lybitel requested changes

2023-05-19 12:42 UTC, hirurg-lybitel requested changes

2023-05-19 12:42 UTC, hirurg-lybitel commented on apps/gdmn-nxt-web/src/app/layouts/MainLayout/Sidebar/menu-collapse/menu-collapse.tsx
> +        style={{ position: 'absolute', visibility: 'hidden' }}
а стиль этот для чего?

2023-05-19 19:48 UTC, sashazernin commented on apps/gdmn-nxt-web/src/app/layouts/MainLayout/Sidebar/menu-collapse/menu-collapse.tsx
> +        style={{ position: 'absolute', visibility: 'hidden' }}
чтобы кнопки не было

2023-05-22 12:40 UTC, sashazernin commented
https://github.com/gsbelarus/gdmn-nxt/tree/menu-with-test-data

2023-05-23 07:52 UTC, hirurg-lybitel requested changes
Во-первых, я не понимаю, как ты тестируешь свои доработки. Тут же ошибки есть
![image](https://github.com/gsbelarus/gdmn-nxt/assets/11502258/7ea6d39a-84f5-402f-b3f1-830c2370e342)

Во-вторых, а как это у меню типа collapse есть может быть url?
Такая кнопка не ведёт же ни на какой адрес

2023-05-23 08:18 UTC, merged

2023-05-23 08:18 UTC, hirurg-lybitel commented
> Во-первых, я не понимаю, как ты тестируешь свои доработки. Тут же ошибки есть ![image](https://user-images.githubusercontent.com/11502258/240068060-7ea6d39a-84f5-402f-b3f1-830c2370e342.png)
> 
> Во-вторых, а как это у меню типа collapse есть может быть url? Такая кнопка не ведёт же ни на какой адрес

@sashazernin обрати внимание на комментарии

2023-05-23 16:25 UTC, sashazernin commented
> Во-первых, я не понимаю, как ты тестируешь свои доработки. Тут же ошибки есть ![image](https://user-images.githubusercontent.com/11502258/240068060-7ea6d39a-84f5-402f-b3f1-830c2370e342.png)
> 
> Во-вторых, а как это у меню типа collapse есть может быть url? Такая кнопка не ведёт же ни на какой адрес

1. да забыл указать key, почему то подумал что ошибка из-за копипаста.