chore: front-end side
gsbelarus/gdmn-nxt pull request #280
Opened 2023-05-26 04:24 UTC by sashazernin

Принимать пулреквест не надо. Пока сделал только фронтенд, @hirurg-lybitel отпиши все ли устраивает.

2023-05-26 07:57 UTC, hirurg-lybitel requested changes
- Информационное окно открывается при каждом входе 
- По коду отметил замечания

А ты на что ориентировался? Чем вдохновлялся? 

Я бы сделал просто отдельным пунктом меню с мастер-детейл гридом. Условно в мастере версия, дата, а в раскрываюшимся детейле вся информация из попапа.

2023-05-26 07:57 UTC, hirurg-lybitel commented on apps/gdmn-nxt-web/src/app/update-list/update-list.module.less
> +.sdasdf{
это точно нужно?

2023-05-26 07:57 UTC, hirurg-lybitel commented on reconciliation-statement/reconciliation-statement.module.less
это что?

2023-05-26 07:57 UTC, hirurg-lybitel commented on reconciliation-statement/reconciliation-statement.spec.tsx
это что?

2023-05-26 07:57 UTC, hirurg-lybitel commented on reconciliation-statement/reconciliation-statement.tsx
это что?

2023-05-26 07:57 UTC, hirurg-lybitel commented on apps/gdmn-nxt-web/src/app/layouts/MainLayout/index.tsx
> +import React, { SyntheticEvent, useEffect, useState } from 'react';
Добавился неисползуемый React

2023-05-26 09:08 UTC, sashazernin commented on apps/gdmn-nxt-web/src/app/update-list/update-list.module.less
> +.sdasdf{
не знаю у меня ошибка выскочила что не может найти модуль и в гите увидел что этих файлов нет

2023-05-26 09:08 UTC, sashazernin commented on reconciliation-statement/reconciliation-statement.module.less
не знаю у меня ошибка выскочила что не может найти модуль и в гите увидел что этих файлов нет

2023-05-26 09:08 UTC, sashazernin commented on apps/gdmn-nxt-web/src/app/update-list/update-list.module.less
> +.sdasdf{
нет удалю

2023-05-26 09:12 UTC, sashazernin commented
@hirurg-lybitel куда поместить кнопку для открытия попапа, и какие нужны поля кроме данных обновления(по типу время создания)?

2023-05-26 09:20 UTC, sashazernin commented on reconciliation-statement/reconciliation-statement.module.less
странно эти файлы и в мейне есть не понятно почему они подстветились как новые

2023-05-26 11:59 UTC, hirurg-lybitel commented
> @hirurg-lybitel куда поместить кнопку для открытия попапа, и какие нужны поля кроме данных обновления(по типу время создания?

зачем эта кнопка?

для мастера номер версии, дата
для детейла контент 

пока других идей нет

2023-05-29 15:46 UTC, hirurg-lybitel requested changes
Очень много ошибок

-[ ] после первого логина
![image](https://github.com/gsbelarus/gdmn-nxt/assets/11502258/274df226-a8ab-4178-8408-141f6554ae85)
- после второго логина под тем же юзером
![image](https://github.com/gsbelarus/gdmn-nxt/assets/11502258/274df226-a8ab-4178-8408-141f6554ae85)
- какая-та неуместная толстая чёрная рамка
![image](https://github.com/gsbelarus/gdmn-nxt/assets/11502258/526957f8-eac3-4b61-ad02-862e492fb931)
- при открытии Истории обновлений в Меню
![image](https://github.com/gsbelarus/gdmn-nxt/assets/11502258/ddbb5e40-ad19-4360-858d-713d5a0170c8)
- какие-то кривые диалоговые окна
![image](https://github.com/gsbelarus/gdmn-nxt/assets/11502258/1ef23cf7-6d1f-4445-82a1-1fab1112dcfd)
- после добавления новая весрия под пользхователем сразу выскакивает окно
![image](https://github.com/gsbelarus/gdmn-nxt/assets/11502258/30b8d6ca-e5d3-4b95-9f16-4b4c010b57f3)
- после удаления последней записи из истории обновления под пользователем, сразу вылазит окно со старым обновлением, которое пользователь уже получал 
![image](https://github.com/gsbelarus/gdmn-nxt/assets/11502258/c34a2878-26a1-49d9-aef1-97d73394ee1e)

2023-05-29 15:47 UTC, hirurg-lybitel commented on apps/gdmn-nxt-web/src/app/pages/UpdatesHistory/Index.tsx
> +export default function FAQ() {
Опять следы копипаста

2023-05-29 15:56 UTC, hirurg-lybitel commented on apps/gdmn-nxt-web/src/main.tsx
> +import UpdatesHistory from './app/pages/UpdatesHistory/Index';
Что это за импорт такой?
Если ты создаёшь файл компонент черех index.tsx, то и импорт тогда `import UpdatesHistory from './app/pages/UpdatesHistory'`

2023-05-29 15:59 UTC, hirurg-lybitel commented on apps/gdmn-nxt-web/src/app/update-list/update-list.tsx
> +    changes: ` # sdfsdfs
Это нужно?

2023-05-29 21:21 UTC, sashazernin commented on apps/gdmn-nxt-web/src/main.tsx
> +import UpdatesHistory from './app/pages/UpdatesHistory/Index';
ошибку выдает
![Uploading image.png…]()

2023-05-29 22:06 UTC, sashazernin commented
> Очень много ошибок
> 
> * [x]  1.после первого логина
>   ![image](https://user-images.githubusercontent.com/11502258/241764285-274df226-a8ab-4178-8408-141f6554ae85.png)
> * [x]  2.после второго логина под тем же юзером
>   ![image](https://user-images.githubusercontent.com/11502258/241764285-274df226-a8ab-4178-8408-141f6554ae85.png)
> * [x]  3.какая-та неуместная толстая чёрная рамка
>   ![image](https://user-images.githubusercontent.com/11502258/241764699-526957f8-eac3-4b61-ad02-862e492fb931.png)
> * [x]  4.при открытии Истории обновлений в Меню
>   ![image](https://user-images.githubusercontent.com/11502258/241765435-ddbb5e40-ad19-4360-858d-713d5a0170c8.png)
> * [x]  5.какие-то кривые диалоговые окна
>   ![image](https://user-images.githubusercontent.com/11502258/241765825-1ef23cf7-6d1f-4445-82a1-1fab1112dcfd.png)
> * [x]  6.после добавления новая весрия под пользхователем сразу выскакивает окно
>   ![image](https://user-images.githubusercontent.com/11502258/241766183-30b8d6ca-e5d3-4b95-9f16-4b4c010b57f3.png)
> * [ ]  7.после удаления последней записи из истории обновления под пользователем, сразу вылазит окно со старым обновлением, которое пользователь уже получал
>   ![image](https://user-images.githubusercontent.com/11502258/241766664-c34a2878-26a1-49d9-aef1-97d73394ee1e.png)

не подразумевалось что обновления будут удалятся. Добавил такую мозможность если к примеру скучайно создал что бы была возможность удалить

2023-05-30 08:24 UTC, hirurg-lybitel commented on apps/gdmn-nxt-web/src/main.tsx
> +import UpdatesHistory from './app/pages/UpdatesHistory/Index';
какую?

2023-05-30 18:16 UTC, hirurg-lybitel requested changes
Ничего не исправлено, всё те же ошибки

2023-05-31 07:12 UTC, sashazernin commented on apps/gdmn-nxt-web/src/main.tsx
> +import UpdatesHistory from './app/pages/UpdatesHistory/Index';
уже не знаю она куда то пропала

2023-05-31 07:53 UTC, sashazernin commented
вообще если изменить название последней версии то она опять выскочит сейчас проверка идет по названию версии обновления т.е если версия записаная у юзера не соответствует названию последней версии в базе то она будет показана.

2023-05-31 12:48 UTC, hirurg-lybitel commented
> есть еще такой момент то если называть версии как попало то сломается сортировка

что значит "как попало"?

2023-05-31 12:52 UTC, hirurg-lybitel commented
> вообще если изменить название последней версии то она опять выскочит сейчас проверка идет по названию версии обновления т.е если версия записаная у юзера не соответствует названию последней версии в базе то она будет показана. Есть 2 варианта:
> 
> 1. Сделать привязку к id поля и останется проблема с удалением
> 2. Сделать отдельную таблицу и записывать видел ли тот или иной юзер обновление

Понятно.
Ладно, в общем оставь данное задание и попробуй сделать следующее.
Это я сам сделаю

2023-05-31 12:57 UTC, hirurg-lybitel commented
> вообще если изменить название последней версии то она опять выскочит сейчас проверка идет по названию версии обновления т.е если версия записаная у юзера не соответствует названию последней версии в базе то она будет показана. Есть 2 варианта:
> 
> 1. Сделать привязку к id поля и останется проблема с удалением
> 2. Сделать отдельную таблицу и записывать видел ли тот или иной юзер обновление

Понятно.
Ладно, в общем оставь данное задание и попробуй сделать следующее.
Это я сам сделаю

2023-05-31 14:15 UTC, sashazernin commented
> И зачем ты разкомментировал код в FAQ, который я уже несколько раз комментировал?

я думал ты закоментировал на время пока с правами разбирался, а так я разкоментировал чтобы сделать страницу с обновлениями и заодо поправить проверку прав на странице faq

2023-05-31 14:15 UTC, sashazernin commented
> > есть еще такой момент то если называть версии как попало то сломается сортировка
> 
> что значит "как попало"?

появлялась ошибка сейчас ее почему то нет

2023-05-31 22:07 UTC, merged