feat: CUD in data grid
gsbelarus/gdmn-nxt pull request #286
Opened 2023-06-05 15:12 UTC by sashazernin

#255

2023-06-06 22:40 UTC, hirurg-lybitel commented
Это законченная доработка?

2023-06-07 09:24 UTC, hirurg-lybitel requested changes
В целом всё неплохо, работает без критических ошибок, НО...

![image](https://github.com/gsbelarus/gdmn-nxt/assets/11502258/93ba7fa3-466a-48af-b32d-6be2b3f3713c)

- [x] 1. Пропал разделитель заголовка страницы
- [x] 2. Стали чёрные иконки
- [x] 3. Абсолютно никакой индикации области ввода теста
- [x] 4. Пропала валидация введённых данных (например, стало возможным сохранить запись с пустыми полями)
- [x] 5. Нет типизации, повсюду сплошные any

2023-06-07 09:25 UTC, hirurg-lybitel commented on apps/gdmn-nxt-web/src/app/pages/Managment/tasksCatalogs/task-types/task-types.tsx
> +                sortModel: [{ field: 'rating', sort: 'desc' }],
снова следы копипастов

2023-06-07 18:25 UTC, sashazernin commented on apps/gdmn-nxt-web/src/app/pages/Managment/tasksCatalogs/task-types/task-types.tsx
> +                sortModel: [{ field: 'rating', sort: 'desc' }],
я хотел добавляемую с помощью сортировки в верх перенести в итоге отказался от этого а удалить забыл

2023-06-07 18:52 UTC, sashazernin commented
Думаю делать на event типизацию не обязательно

2023-06-07 23:54 UTC, hirurg-lybitel commented
> Думаю делать на event типизацию не обязательно

В своих личных проектах можешь везде any ставить, но в наших рабочих на больше, чем одного разработчика, хотелось бы хотя бы получать вразумительное обоснование для использования any в параметрах функции.

2023-06-08 15:11 UTC, merged

2023-06-08 17:27 UTC, sashazernin commented
а почему ты смерждил комит если я еще ничего не поправил

2023-06-08 17:28 UTC, sashazernin commented
> > Думаю делать на event типизацию не обязательно
> 
> В своих личных проектах можешь везде any ставить, но в наших рабочих на больше, чем одного разработчика, хотелось бы хотя бы получать вразумительное обоснование для использования any в используемых параметрах функций.

до этого на ивенты же не ставили типизацию