input at full height
gsbelarus/gdmn-nxt pull request #291
Opened 2023-06-12 20:48 UTC by sashazernin

[#288](https://github.com/gsbelarus/gdmn-nxt/issues/288)

2023-06-13 13:19 UTC, hirurg-lybitel requested changes
Вот ты сделал, что всё красиво растягивается - это хорошо.

Потом ты проверяешь, что сделал, и вводишь большой текст, не помещающийся в области видимости:
![image](https://github.com/gsbelarus/gdmn-nxt/assets/11502258/72c232ce-1ca0-40db-9114-956e0dab4ad6)

И тебя правда не смутило ничего?
Нет ни индикации никакой, что есть ещё текст, который не виден, ни возможности как-то прокрутить к этому тексту

2023-06-13 18:18 UTC, sashazernin commented
> Вот ты сделал, что всё красиво растягивается - это хорошо.
> 
> Потом ты проверяешь, что сделал, и вводишь большой текст, не помещающийся в области видимости: ![image](https://user-images.githubusercontent.com/11502258/245488880-72c232ce-1ca0-40db-9114-956e0dab4ad6.png)
> 
> И тебя правда не смутило ничего? Нет ни индикации никакой, что есть ещё текст, который не виден, ни возможности как-то прокрутить к этому тексту

я посмотрел что текст вводится дальше. Прокрутку забыл проверить, а отсутствию скролла не придал значения.

2023-06-14 00:00 UTC, hirurg-lybitel requested changes
Всё хорошо, но получится ли сделать компонент растягиваемым на всю доступную высоту, чтобы не указывать каждый раз -30px, а то это не очень реюзаьбельно?

2023-06-14 18:43 UTC, hirurg-lybitel commented
убрал ненужные стили в коде

2023-06-15 12:03 UTC, merged