feat: phone number validation
gsbelarus/gdmn-nxt pull request #302
Opened 2023-06-28 17:52 UTC by sashazernin

#294

2023-06-29 18:46 UTC, hirurg-lybitel requested changes
Что в этом номере некорректного?
![image](https://github.com/gsbelarus/gdmn-nxt/assets/11502258/a0096527-c1e4-4910-b2b3-2f5105094e1c)

2023-07-04 16:52 UTC, hirurg-lybitel approved these changes
Опять некачественная проверка...
Разве такой номер может быть валидным?

![image](https://github.com/gsbelarus/gdmn-nxt/assets/11502258/000fa9a5-364f-4b57-8c0e-c6fe914c80cb)

2023-07-04 16:56 UTC, hirurg-lybitel commented
Я добавил текстфилд с маской, но закоментировал его, чтобы ты мог валидацию доделать.
Как сделаешь рабочую валидацию, попробуй её применить с новым компонентом `TextFieldMaskedProps`

2023-07-04 17:27 UTC, hirurg-lybitel requested changes
Случайно апрувнул

2023-07-05 20:56 UTC, sashazernin commented
> Опять некачественная проверка... Разве такой номер может быть валидным?
> 
> ![image](https://user-images.githubusercontent.com/11502258/250957188-000fa9a5-364f-4b57-8c0e-c6fe914c80cb.png)

А разве нет?

2023-07-05 21:08 UTC, sashazernin commented
> Опять некачественная проверка... Разве такой номер может быть валидным?
> 
> ![image](https://user-images.githubusercontent.com/11502258/250957188-000fa9a5-364f-4b57-8c0e-c6fe914c80cb.png)

А в чем проблема?

2023-07-06 09:35 UTC, hirurg-lybitel commented
> > Опять некачественная проверка... Разве такой номер может быть валидным?
> > ![image](https://user-images.githubusercontent.com/11502258/250957188-000fa9a5-364f-4b57-8c0e-c6fe914c80cb.png)
> 
> А в чем проблема?

в какой стране номера начинаются с нуля?

2023-07-07 12:43 UTC, hirurg-lybitel requested changes
Сойдёт.
Теперь сделай с маской, проверь нормально и распространи на все формы с номером.

2023-07-10 18:54 UTC, merged