feat: short name, creator field, sorting
gsbelarus/gdmn-nxt pull request #336
Opened 2023-07-11 16:46 UTC by sashazernin

#327

2023-07-11 21:23 UTC, hirurg-lybitel requested changes
Я же сказал, что не брать никнейм из сервера!

2023-07-12 18:42 UTC, sashazernin commented
> @sashazernin Я же сказал, что не брать никнейм из сервера!

не увидел

2023-07-12 20:50 UTC, sashazernin commented
Писал же что по USR$CREATIONDATE надо сортировать

2023-07-12 20:53 UTC, hirurg-lybitel commented
> Писал же что по USR$CREATIONDATE надо сортировать

Алексей решил, что на данный момент информативней будет по сроку сортировать

2023-07-12 20:53 UTC, merged