feat: tooltip for kanban cards
gsbelarus/gdmn-nxt pull request #342
Opened 2023-07-13 15:04 UTC by sashazernin

#320

2023-07-14 13:02 UTC, hirurg-lybitel requested changes
С тултипом хорошо получилось, но...

- [x] 1. Не надо выводить Нет активных задач, если задач нет. Это и так видно
![image](https://github.com/gsbelarus/gdmn-nxt/assets/11502258/584f7f83-f365-4d32-81ae-8eef3c94e4e3)

- [ ] 2. В задаче со сроком исполнения Сегодня какой-то ноль
![image](https://github.com/gsbelarus/gdmn-nxt/assets/11502258/2cceb94a-2215-433c-9fa6-d414c16c1634)

- [ ] 3. Чёрный текст на тёмном фоне не очень читаемый. Плюс шрифты разные зачем-то. И почему вообще только активные задачи? Должен быть весь всписок 
![image](https://github.com/gsbelarus/gdmn-nxt/assets/11502258/940abef4-5a7f-4b71-a324-90a0e28f6b28)

- [ ] 4. Не надо переносить "56 дней"
![image](https://github.com/gsbelarus/gdmn-nxt/assets/11502258/e0aa068f-44b2-4a5e-a733-446026f971c2)

2023-07-14 17:20 UTC, sashazernin commented
> С тултипом хорошо получилось, но...
> 
> * [x]  1. Не надо выводить Нет активных задач, если задач нет. Это и так видно
>   ![image](https://user-images.githubusercontent.com/11502258/253574190-584f7f83-f365-4d32-81ae-8eef3c94e4e3.png)
> * [x]  2. В задаче со сроком исполнения Сегодня какой-то ноль
>   ![image](https://user-images.githubusercontent.com/11502258/253574953-2cceb94a-2215-433c-9fa6-d414c16c1634.png)
> * [x]  3. Чёрный текст на тёмном фоне не очень читаемый. Плюс шрифты разные зачем-то. И почему вообще только активные задачи? Должен быть весь всписок
>   ![image](https://user-images.githubusercontent.com/11502258/253574594-940abef4-5a7f-4b71-a324-90a0e28f6b28.png)
> * [x]  4. Не надо переносить "56 дней"
>   ![image](https://user-images.githubusercontent.com/11502258/253577458-e0aa068f-44b2-4a5e-a733-446026f971c2.png)

на счет ноля что то старанное сначала выдавало -0 как deadline а потом при !!deadline выдавало false хотя он есть.

2023-07-14 20:50 UTC, sashazernin commented
В общем у меня получилось сделать скролбар в подсказке. Для определения высоты подсказки использую точно такой же компонент но только скрываю его.

2023-07-14 20:51 UTC, sashazernin commented
> В общем у меня получилось сделать скролбар в подсказке. Для определения высоты подсказки использую точно такой же компонент но только скрываю его.

но есть проблема с тем что скролл есть у каждой подсказки есть исли проматать то он пропадает то он пропадает.
![image](https://github.com/gsbelarus/gdmn-nxt/assets/94962537/22cfe42e-db7b-426f-ad15-42c5bb9af4bc)

2023-07-15 01:20 UTC, sashazernin commented
У меня получилось сделать скролл для подсказок но есть проблема со скролом он есть там где скролить нильзя, если проскролить подсказку то он сразу пропадает.

2023-07-17 10:39 UTC, hirurg-lybitel requested changes
1. А что за такие огромные пустые пространства?
![image](https://github.com/gsbelarus/gdmn-nxt/assets/11502258/e89b4db2-eca5-49d0-bb1a-7e8f22d1a15c)

2. Почему в одном и том же случае с единственной задачей совершенно разные отступы?
![image](https://github.com/gsbelarus/gdmn-nxt/assets/11502258/572aac09-7fe7-49a9-b288-2e0dde542343)
![image](https://github.com/gsbelarus/gdmn-nxt/assets/11502258/e076834f-0578-49f9-a2ca-903dc16a8849)

2023-07-17 10:44 UTC, sashazernin commented
> 1. А что за такие огромные пустые пространства?
>    ![image](https://user-images.githubusercontent.com/11502258/253916080-e89b4db2-eca5-49d0-bb1a-7e8f22d1a15c.png)
> 2. Почему в одном и том же случае с единственной задачей совершенно разные отступы?
>    ![image](https://user-images.githubusercontent.com/11502258/253916510-572aac09-7fe7-49a9-b288-2e0dde542343.png)
>    ![image](https://user-images.githubusercontent.com/11502258/253916410-e076834f-0578-49f9-a2ca-903dc16a8849.png)

странно, у меня все нормально было, щас гляну.

2023-07-17 10:51 UTC, sashazernin commented
>

2023-07-17 10:52 UTC, sashazernin commented
> 3. По поводу скролла., раз уж он есть. Сколько в итоге надо задач, чтобы контейнер прокручивался?
>    ![image](https://user-images.githubusercontent.com/11502258/253917837-ebc0f4f7-17de-45ce-acd6-6bb2f4115389.png)

Зависит от высоты экрана, чем больше экран тем больше поместится записей.

2023-07-17 11:01 UTC, hirurg-lybitel commented
> > 3. По поводу скролла., раз уж он есть. Сколько в итоге надо задач, чтобы контейнер прокручивался?
> >    ![image](https://user-images.githubusercontent.com/11502258/253917837-ebc0f4f7-17de-45ce-acd6-6bb2f4115389.png)
> 
> Зависит от высоты экрана, чем больше экран тем больше поместится записей.

на всю высоту браузера растягиваться будет что ли??

2023-07-17 11:01 UTC, sashazernin commented
> на всю высоту браузера растягиваться будет что ли??

90vh

2023-07-18 07:06 UTC, hirurg-lybitel requested changes
Переделал всё же на раскрывающийся список.

Тут пару моментов новых тепер:

1. Перехватывать прокуртку колеса мыши на гриде, чтобы прокуртывался именно грид, если курсор на нём, а не контейнер с карточками.
![image](https://github.com/gsbelarus/gdmn-nxt/assets/11502258/5870d92f-d563-4d73-87f7-2343096a93b9)

2. Выровнять отступы 1 и 2
![image](https://github.com/gsbelarus/gdmn-nxt/assets/11502258/2ba57dc6-63a5-48d2-9420-3d7e6798be50)

3. Так же выровнять отсутпы 1 и 2. Вообще колонка с информацией о сроке должна растягиватьяс на ширину саммой широкой ячейки, а не с таким запасом, как на скрине
![image](https://github.com/gsbelarus/gdmn-nxt/assets/11502258/ed388bee-20ab-4511-8760-862aa0add2c0)

2023-07-19 13:21 UTC, sashazernin commented
со стилями разобрался а вот со скролом не получилось

2023-07-20 13:43 UTC, merged