feat: navigate from tast to deal
gsbelarus/gdmn-nxt pull request #363
Opened 2023-07-29 09:51 UTC by sashazernin

#348

2023-07-31 09:51 UTC, hirurg-lybitel requested changes
1. Не соответсвует логике работы, описанной в задании 
2. Не надо делать через Button, если это просто ссылка. Это же все стили сломало

2023-07-31 11:46 UTC, sashazernin commented
> 1. Не соответсвует логике работы, описанной в задании
> 2. Не надо делать через Button, если это просто ссылка. Это же все стили сломало

1. Логика работы описана не была в ишью, пожалуйста опиши как это должно работать

2023-07-31 17:38 UTC, sashazernin commented
> 1. Не соответсвует логике работы, описанной в задании
> 2. Не надо делать через Button, если это просто ссылка. Это же все стили сломало

не знаю как еще можно интерпретировать "перейти на сделку"

2023-08-01 16:44 UTC, hirurg-lybitel commented
В приницпе всё хорошо работает, но очень спорное решение с переходом на страницу сделок, созданием какого-то отдельного стора и увеличением размера овтетов от сервера.

Чтобы не мучаться с ревертами, просто отклоняю этот реквест и переделаю попроще

2023-08-01 16:44 UTC, closed without merging

2023-08-01 20:26 UTC, sashazernin commented
Я тоже думал что создавать отдельный слайд ради одного значение не то, но слайс фильтров как мне показалось не подходил, и юзконтекст тоже т.к. это две разные компоненты.