fix: add menuBar open button
gsbelarus/gdmn-nxt pull request #368
Opened 2023-08-02 12:02 UTC by sashazernin

#362

2023-08-02 21:54 UTC, hirurg-lybitel requested changes
при открытии меню дайлогом, зачем-то происходит ресайз контента на фоне
![video](https://github.com/gsbelarus/gdmn-nxt/assets/11502258/300901fa-111b-42b7-b358-12e5b9fd3900)

2023-08-02 21:57 UTC, hirurg-lybitel commented on apps/gdmn-nxt-web/src/app/layouts/MainLayout/index.tsx
> +      marginLeft: -(theme.drawerWidth - (window.innerWidth < 900 ? 60 : 20)),
что вообще такое "900"? Откуда оно взялось?

2023-08-03 10:09 UTC, sashazernin commented on apps/gdmn-nxt-web/src/app/layouts/MainLayout/index.tsx
> +      marginLeft: -(theme.drawerWidth - (window.innerWidth < 900 ? 60 : 20)),
Это ширина экрана при которой меню становится попапом

2023-08-03 11:25 UTC, sashazernin commented
Единственное не знаю в каком месте потом удалять слушатель события

2023-08-04 08:33 UTC, hirurg-lybitel commented on apps/gdmn-nxt-web/src/app/layouts/MainLayout/index.tsx
> +      marginLeft: -(theme.drawerWidth - (window.innerWidth < 900 ? 60 : 20)),
Я понимаю. Но почему 900?
нельзя приваязыватсья к какому-то числу просто так в коде. Если этой брейкпойнт, то к брейкпойнту и привязываться

2023-08-04 08:39 UTC, hirurg-lybitel commented
> Единственное не знаю в каком месте потом удалять слушатель события

зачем вообще какие-то листенеры?

2023-08-04 10:44 UTC, sashazernin commented
> > Единственное не знаю в каком месте потом удалять слушатель события
> 
> зачем вообще какие-то листенеры? У нас же всё построено на брейкпойнтах и обработке их изменений

иначе при изменении окна не будет компонент обновляться

2023-08-04 12:31 UTC, hirurg-lybitel commented
> > > Единственное не знаю в каком месте потом удалять слушатель события
> > 
> > 
> > зачем вообще какие-то листенеры? У нас же всё построено на брейкпойнтах и обработке их изменений
> 
> иначе при изменении окна не будет компонент обновляться

при изменении окна должен меняться брейкпойнт и, соответственно, перерисовываться всё, что связано с ним. Не нужны по идее никакие листенеры. Менялось же меню без них

2023-08-07 18:41 UTC, merged