Deals. scroll
gsbelarus/gdmn-nxt pull request #398
Opened 2023-09-14 03:01 UTC by sashazernin

#394

2023-09-14 04:00 UTC, sashazernin commented
#388

2023-09-14 09:17 UTC, hirurg-lybitel commented
> #394

Вроже же нормально написал, что скрол сместить правее, а не компоненты левее 

Теперь вот отступы какие-то получились 
![image](https://github.com/gsbelarus/gdmn-nxt/assets/11502258/4df6cfbd-a280-486a-82c0-74ae504cd840)

2023-09-14 09:18 UTC, hirurg-lybitel requested changes
Вроде же нормально написал, что скрол сместить правее, а не компоненты левее

Теперь вот отступы какие-то получились
![image](https://github.com/gsbelarus/gdmn-nxt/assets/11502258/90dc474b-a13c-45fa-8439-599bb19c4ef8)

2023-09-15 23:46 UTC, hirurg-lybitel requested changes
Не понял подхода по смещение скролла вправо. Много ненужных элементов и стилей добавлено

2023-09-15 23:56 UTC, merged