fix: logout after AFK
gsbelarus/gdmn-nxt pull request #414
Opened 2023-09-15 18:34 UTC by sashazernin

#401

2023-09-18 13:24 UTC, hirurg-lybitel requested changes
Проект просто не запускается

![image](https://github.com/gsbelarus/gdmn-nxt/assets/11502258/896620b6-2492-4f3f-a479-6a21e28c84e3)

2023-09-18 13:29 UTC, sashazernin commented
> Проект просто не запускается
> 
> ![image](https://user-images.githubusercontent.com/11502258/268658047-896620b6-2492-4f3f-a479-6a21e28c84e3.png)

странно у меня все нормально работает

2023-09-18 13:58 UTC, hirurg-lybitel commented
> > Проект просто не запускается
> > ![image](https://user-images.githubusercontent.com/11502258/268658047-896620b6-2492-4f3f-a479-6a21e28c84e3.png)
> 
> странно у меня все нормально работает

ничего странного, ты добавил циклические зависимости в проект

2023-09-18 21:10 UTC, sashazernin commented
я не вижу циклических зависимосте, и у меня такой ошибки нет

2023-09-20 21:18 UTC, sashazernin commented
> > я не вижу циклических зависимосте, и у меня такой ошибки нет
> 
> а как ты смотришь/проверяешь? у тебя сейчас gdmn-nxt-web зависит от libs, а libs от gdmn-nxt-web

забыл удалить н

2023-09-25 12:07 UTC, hirurg-lybitel requested changes
Логаут происходит при незалогиненном юзере

2023-09-25 17:52 UTC, hirurg-lybitel requested changes

2023-09-25 17:52 UTC, hirurg-lybitel commented on apps/gdmn-nxt-web/src/app/layouts/MainLayout/index.tsx
> +    timeout: 1000 * 2,
2 секунды - это как-то совсем беспощадно. Поставь хотя бы 20 минут

2023-09-25 18:49 UTC, sashazernin commented on apps/gdmn-nxt-web/src/app/layouts/MainLayout/index.tsx
> +    timeout: 1000 * 2,
ой да, забыл вернуть)

2023-09-26 11:32 UTC, merged