feat: number mask for other countries
gsbelarus/gdmn-nxt pull request #437
Opened 2023-10-13 14:03 UTC by sashazernin

https://github.com/gsbelarus/gdmn-nxt/issues/429

2023-10-13 14:04 UTC, sashazernin commented
Надо очищать поле с номером при смене страны, не получилось найти как это делать в формике

2023-10-16 06:58 UTC, hirurg-lybitel requested changes
![image](https://github.com/gsbelarus/gdmn-nxt/assets/11502258/8e808295-a594-43c1-bafd-21c1f83aa780)

Попытка интересная, но сразу несколько вопросов:
- не видно, собственно, выбранной страны
- маску надо будет руками каждый раз прописывать при добавлении нового региона?
- и главный - ты же вот пользуешься интернетом, регистрируешься на всяих ресурах. Ты где-нибудь вообще видел такое решение?)

На самом деле ведь это максимаьлно тривиальная задача, решения по которой уже давно доведены до совершенства, и колесо тут точно не надо выдумывать. 

Полно даже готовых компонентов:
![image](https://github.com/gsbelarus/gdmn-nxt/assets/11502258/9018c93f-0ae1-4d8b-83aa-547e3111d6e1)

2023-10-16 07:00 UTC, hirurg-lybitel commented
В общем, я, пожалуй, сам тогда сегодня накидаю решение, чтобы проще было

2023-10-16 16:46 UTC, hirurg-lybitel commented
Решено в PR  https://github.com/gsbelarus/gdmn-nxt/pull/438

2023-10-16 16:46 UTC, closed without merging