Marks
gsbelarus/gdmn-nxt pull request #454
Opened 2023-11-15 15:38 UTC by sashazernin

#427

2023-12-17 22:19 UTC, hirurg-lybitel requested changes
1. Код не соответсвует правилам eslint
2. При наведении всё равно отображается короткое наименование. И не надо обрезать навазние метки. Надо ограничить максимальну длину самого названия, а при наведении выводить описание

2023-12-17 22:19 UTC, hirurg-lybitel commented on package.json
> +    "react-window": "^1.8.9",
для чего эта библиотека?

2023-12-17 22:19 UTC, hirurg-lybitel commented on apps/gdmn-nxt-web/src/app/components/IconSelect/Icon-select.tsx
Неудобный узкий поиск. 
![image](https://github.com/gsbelarus/gdmn-nxt/assets/11502258/4c61c255-ff60-4e43-b549-48e17914dded)

Должна быть плитка, хотя бы как на самом сайте mui

2023-12-18 18:54 UTC, hirurg-lybitel requested changes
Полностью проигнорирован пункт 2 предыдущего комментария.

2023-12-18 18:54 UTC, hirurg-lybitel commented on apps/gdmn-nxt-web/src/app/features/common/useOutsideClick.ts
> +  const ref2 = useRef<any>();
что такое ref2? такие названия ни о чём не говорят другим людям

2023-12-18 19:09 UTC, sashazernin commented
> 1. Код не соответсвует правилам eslint
> 2. При наведении всё равно отображается короткое наименование. И не надо обрезать навазние метки. Надо ограничить максимальну длину самого названия, а при наведении выводить описание

![image](https://github.com/gsbelarus/gdmn-nxt/assets/94962537/db5814df-446b-41c5-9b35-f98a84f520bc)

отображается же полное назание

2023-12-19 17:45 UTC, hirurg-lybitel commented
> Если ограничить сам компонент то будет не очень понятно что это вся метка. Вот тут получается метка ИНФОРМАL
> 
> При наведении отображается полное название или отображать описание при наведении на метку на странице меток?


> При наведении всё равно отображается короткое наименование. И не надо обрезать навазние метки. Надо ограничить максимальну длину самого названия, а при наведении выводить описание

Так про ограничение компонента ничего не сказано. Наоборот написал же, что не нажо обрезать ничего, а выводить полностью название. Вот само название и ограничить, чтобы нельзя было ввести более 30 символов, например.

Так же написал, чотбы выводить **описание** при наведении

2023-12-20 12:53 UTC, hirurg-lybitel requested changes
Всё ещё полностью проигнорирован пункт про eslint

2023-12-20 17:41 UTC, hirurg-lybitel requested changes
Это уже как прикол какой-то. Всё ещё несоответсвие eslint, хотя он сам предлагает поправить код, согласно правилам.

Сам исправилю уже

2023-12-20 17:43 UTC, sashazernin commented
> Это уже как прикол какой-то. Всё ещё несоответсвие eslint, хотя он сам предлагает поправить код, согласно правилам.
> 
> Сам исправилю уже

ну я вроде во всех в которых работал поисправлял, надо будет в json прописать добавить команду для форматирования всех файлов

2023-12-20 18:12 UTC, merged