fix: infinite re-render
gsbelarus/gdmn-nxt pull request #465
Opened 2023-12-27 01:46 UTC by sashazernin

https://github.com/gsbelarus/gdmn-nxt/issues/461

2023-12-27 13:13 UTC, hirurg-lybitel requested changes
То есть ты просто сделал вместо удобного многострочного отображения данных однострочное текстовое поле, в которое не влазят данные?

Это, мягко говоря, не решение проблемы. Особенно, учитыая, что раньше всё работало нормально.

Поэтому нужно сначала выяснить, в чём проблема, п отом придумать нормальное решенние без потери функционала

2023-12-27 15:02 UTC, sashazernin commented
> То есть ты просто сделал вместо удобного многострочного отображения данных однострочное текстовое поле, в которое не влазят данные?
> 
> Это, мягко говоря, не решение проблемы. Особенно, учитыая, что раньше всё работало нормально.
> 
> Поэтому нужно сначала выяснить, в чём проблема, п отом придумать нормальное решенние без потери функционала

почитал проблема в multiline в компоненте пофиксить можно просто убрав его

2023-12-27 15:47 UTC, hirurg-lybitel commented
А что насчёт самим расчёт делать?

2023-12-27 15:50 UTC, sashazernin commented
> Раньше же понимал как-то. А что насчёт самим расчёт делать?

не знаю нашел обсуждение на гите на этот счет все пишут что если row не указывать то ошибка будет. а растет самому можно, тогда сделаю свой расчет.

2023-12-27 16:55 UTC, sashazernin commented
сделал свой расчет но что то при изменении количества строк опять ошибка вылазит, мне кажется проще просто задать размер 2 и все.

2024-01-03 09:58 UTC, hirurg-lybitel commented
понятно

2024-01-03 11:13 UTC, merged