a user group line with multiple users adding
gsbelarus/gdmn-nxt pull request #476
Opened 2024-01-12 02:12 UTC by sashazernin

#473

2024-01-12 02:12 UTC, gsbelarus commented on apps/gdmn-nxt-server/src/app/controllers/permissions.ts
>  };
### Review Summary
- **ID Parsing**: Parsing the `id` from `req.params.id` without further validation on non-POST methods could pose a risk of SQL injection if used within SQL queries directly.
- **Commented Code**: Large blocks of commented-out code should be removed before merging to keep the codebase clean and maintainable. Having commented-out logic like the `userExistsQuery` can cause confusion later on.
- **Error Handling**: Catching errors and only returning `error.message` might inadvertently expose sensitive information or implementation details. Make sure error messages are user-friendly and don't reveal system internals.
- **Potential Loop Inefficiency**: Asynchronous tasks inside a loop, specifically `Promise.all(querys.map(execQuery))`, can be inefficient if not batched properly outside the loop.
- **Data Validation & Type Safety**: Before using `req.body` fields, it's crucial to validate and sanitize incoming data to prevent type-related issues or security vulnerabilities.
- **Unhandled Promise**: The call to `closeUserSession()` inside the second loop doesn't handle the promise it may return, potentially ignoring its failure.
- **Consistency**: The function `releaseTransaction()` is being awaited with no clear guarantee that its return value (`true` or `false`) is being handled correctly based upon `res.statusCode`.
- **HTTP Status Codes**: The use of HTTP status codes seems appropriate, but ensure consistency throughout the application for similar cases.
- **Transactions**: Ensure transactional integrity by checking that all individual operations within the 'try' block are atomic and can be rolled back in case of errors.
- **Duplicate IDs**: The logic implies that users can exist in only one group at a time based on the commented code. If that's a requirement, then the check should be re-enabled and validated.
- **Security**: There's no apparent input sanitization which could lead to injection attacks.
- **Hardcoded Schema References**: The direct reference to `TgdcAttrUserDefinedUSR_CRM_PERMISSIONS_UG_LINES` suggests tight coupling with the schema, consider abstracting it.

Overall, there are numerous areas of potential concern, particularly regarding data validation, security practices, and performance optimizations.

Quality Rate: 4/10

2024-01-12 02:13 UTC, gsbelarus commented on apps/gdmn-nxt-server/src/app/routes/permissionsRouter.ts
>  router.get('/actions', PermissionsController.getActions);
### Code Review
- It appears that there are inconsistent naming conventions in the routes: `'/userGroups'` and `'/'usersgroupsline'`. Consistency should be maintained.
- The addition of `router.post('/usersgroupsline', PermissionsController.upsertUsersGroupLine);` seems fine, but ensure that it doesn't lead to duplicate functionality with existing endpoints.
- Make sure that proper validation is set up within `PermissionsController.upsertUsersGroupLine` to avoid security vulnerabilities like SQL injection or invalid data entry.
- Verify that authentication and authorization checks are properly applied to this new route to ensure that only authorized users can access it.
- For improved readability and maintainability, consider separating the routes into different modules or files based on their responsibility or domain.

Note: without context or seeing more of the code it's difficult to fully assess security risks or potential bugs. This review is based on the given code snippet only.

Quality Rate: 6/10

2024-01-12 02:14 UTC, gsbelarus commented on apps/gdmn-nxt-web/src/app/components/Permissions/user-group-line-edit/user-group-line-edit.tsx
>          </FormikProvider>
### Code Review 

#### **General Overview**
- The patch introduces changes where multiple user group lines can be added or removed dynamically.
- Uses React hooks, Formik for form handling, and Material-UI components.

#### **Potential Issues**
- **Consistency and Clarity**: The variable `forms` is confusingly named. It represents the IDs for each form entry but sounds like it might store forms themselves. Consider renaming to `formEntryIds` for clarity.
- **State Management**: A unique ID system for form entries has been introduced, which relies on incrementing the last ID in the list. However, there's no check if an ID already exists which might be an issue if state is ever managed differently.
- **Validation Schema**: Each new user form field needs to be validated, but the validation schema only mentions `USER1`. Validations don't scale with dynamic forms. You may need to generate the schema dynamically based on `forms`.
- **Error Handling**: No error handling in place if the `onSubmit` fails, potentially leaving the user unaware of submission failure or app in inconsistent state.
- **Performance**: For every form added, every input rerenders because the entire form shares one `formik` state. Could be performance-heavy with lots of users.
- **Accessibility**: IconButton does not have a proper `aria-label`, affecting screen reader users.

#### **Security Concerns**
No direct security vulnerabilities are observable in the given patch, although depending on the rest of the implementation, making sure that user actions are properly authenticated and authorized is crucial.

#### **Suggestions**
- Dynamically create the validation schema to include all dynamically added user fields (e.g., USER2, USER3, etc.) when the form is submitted.
- Introduce error handling for submission issues.
- Consider optimizing form re-renders. Maybe utilize `useField` or separate formik instances per row if necessary.
- Add proper `aria-labels` for all actionable icons for accessibility compliance.

#### **Best Practices**
- Make sure to remove any sensitive data from autocomplete options before presenting them to the client side.
- Ensure consistent use of UI components; maintain the same styling for buttons and other interface elements.

Overall, this code shows a basic dynamic form implementation but requires improvements in terms of scalability, performance, and user experience.

Quality Rate: 5/10

2024-01-12 02:14 UTC, gsbelarus commented on apps/gdmn-nxt-web/src/app/const.ts
>  export const baseUrlApi = `${baseUrl}api/v1/`;
The code patch shows a reversion to previous logic for constructing the `baseUrl`. The change includes server port in the URL if defined.

**Review points:**
1. Reintroducing `config.serverPort` is a functional change and could be necessary if services are running on non-standard ports. It increases flexibility.
2. If `serverPort` is an empty string or undefined, the port segment is omitted, preventing unnecessary colon appearance in the URL (e.g., `https://host:/`).
3. By commenting out the previous line and not removing it, developers can quickly revert or compare with the older version. However, it might be better to have proper version control rather than commented-out code.
4. The code assumes HTTPS protocol, which implies security by default, but there may be use cases where HTTP is required.
5. No input validation or sanitation is evident. If `config.serverHost` is user-provided, this may introduce security risks.
6. There's no error handling to ensure `config.serverHost` is well-formed.

**Possible Improvements:**
- Ensure through code review or additional checks that `config.serverHost` and `config.serverPort` contain safe, expected values.
- Consider support for HTTP if needed, while defaulting to HTTPS.
- Remove commented-out code if version control is used.
- Implement error handling for malformed host or port values.

Overall, the change presents no immediate red flags but lacks context on configuration values' safety and potential need for HTTP support.

Quality Rate: 7/10

2024-01-12 02:15 UTC, gsbelarus commented on apps/gdmn-nxt-web/src/app/features/permissions/index.ts
>    useDeleteUserGroupLineMutation,
## Review Summary

1. **Ambiguity in Function Naming:** 
The newly added mutation function `addUsersGroupLine` is confusing since there's already an `addUserGroupLine`. If they have different purposes, the naming should reflect these distinctions to avoid confusion.

2. **Type Consistency:**
The new mutation takes a partial array of `IUserGroupLine`, hinting that it could accept multiple group lines or incomplete data. This contrast with `updateUserGroupLine`, which accepts a single, partial user group line object. Ensure that this was intentional and aligns with the backend expectations.

3. **Validation & Error Handling:**
It's not clear if the body content of `addUsersGroupLine` mutation is validated before being sent to the server. Proper validation should be implemented to prevent potential security vulnerabilities or logic errors.

4. **Tag Invalidations Consistency:**
The invalidation tag `{ type: 'Users', id: 'LIST' }` appears identical for both adding and updating operations. This configuration may lead to unnecessary cache refreshes. Consider making your cache invalidation strategy more granular if performance becomes an issue.

5. **Lack of Comments:**
The patch lacks comments explaining the purpose and usage of the new mutation, which would be beneficial for future maintenance and understanding the code.

6. **Test Coverage:**
There is no indication that new tests were added along with this code change. It’s important to update or add tests to cover the new functionality adequately.

7. **RESTful API Design:**
By looking at the URL 'permissions/usersgroupsline', it seems that RESTful conventions might not be strictly followed. Typically, resources are named using the singular form, and their collection is implied when you POST to them.

## Improvement Suggestions
- Rename the `addUsersGroupLine` mutation for clarity and distinction from existing mutations.
- Add input validation and thorough error handling to the mutation function.
- Update tests to include the new mutation.
- Review and optimize cache invalidation tags.
- Add comments to the code to explain the new mutation implementation.
- Ensure endpoint URLs follow best practices in RESTful API design.

Quality Rate: 5/10

2024-01-12 02:15 UTC, gsbelarus commented on apps/gdmn-nxt-web/src/app/pages/Permissions/user-groups/user-groups.tsx
>                <Button
- The patch introduces a new mutation `useAddUsersGroupLineMutation` but the corresponding deletion or update mutations for multiple lines are not introduced. This might be an inconsistency if there's functionality to delete or update individual lines but not multiple at once.
- The change from single to multiple (`userGroupLine` to `usersGroupLine`) suggests a fundamental change in how submissions are handled. This should be thoroughly tested, especially if other parts of the application expect the single-line submission format.
- Updating the handler function to accept an array (`IUserGroupLine[]`) instead of a single object may lead to issues if the API endpoint doesn't support batch operations or if it hasn't been properly tested.
- The code formatting within the React component skeletons and stacks has been improved by breaking down props into multiple lines, which enhances readability.
- There is no check on the data structure being submitted in `addUsersGroupLine(usersGroupLine);`. It should ideally validate that it's receiving an array of `IUserGroupLine` objects to prevent potential bugs.
- Without knowing the broader context, the removal of one element from the imports (`useDeleteUseGroupMutation`) and introduction of another (`useAddUsersGroupLineMutation`) hints at a change in functionality that should be double-checked for accuracy and necessity.
- There are no visible security issues in the changed code, although without seeing the actual implementation of the mutation functions, this cannot be conclusively determined.
- Please ensure there are proper error handling mechanisms for the asynchronous `handleOnSubmit` which now handles multiple group lines.

**Recommendation:**
- Thorough testing is warranted for these changes.
- Ensure there's equivalent functionality for deleting and updating multiple user group lines, not just adding them.
- Confirm with backend/API teams that the batch operation is supported.
- Implement validation and error handling for the new batch submission.

Quality Rate: 6/10

2024-01-12 02:15 UTC, gsbelarus commented on libs/config/src/lib/config.ts
>    host,
### Code Review

#### Observations:
- The change re-introduces `appPort` into the `origin` URL, which might have been removed intentionally or unintentionally in a previous patch.
- The port should only be included if different from the default HTTPS port (443). Including the default port is redundant.
- If `appPort` is expected to be something other than 443, the added line makes sense. However, it should check if `appPort` is truly set to avoid appending an empty or undefined value in the URL.
- The commented-out code should ideally be removed before committing if the decision has been made to adopt the new line of code; keeping old code as comments can clutter and confuse the codebase.

#### Security Implications:
- There are no direct security implications in this diff unless the configuration is sensitive to whether the port is specified.

#### Improvement Suggestions:
- Ensure that ports are only appended to URLs when necessary and consider utilizing environment variables for toggling between including the port in various environments.
- Remove commented code that is no longer intended to be used to maintain clarity.
- Validate that `appPort` contains a valid port number before using it in the `origin` string to avoid potential run-time issues.


Quality Rate: 7/10

2024-01-12 02:37 UTC, gsbelarus commented on apps/gdmn-nxt-server/src/app/controllers/permissions.ts
>  };
### Code Review Summary

#### Code Quality Rate: 3/10

#### Bugs/Risks
- **Parsing `id` Without Validation:** There is parsing of `req.params.id` without subsequent validation checks (validation logic is commented out).
- **Insecure Equality Check:** Using `==` instead of `===` can lead to type coercion issues.
- **Transaction Error Handling:** If any of the execQuery promises fail, others will still run, potentially leading to inconsistent state.
- **Magic Strings:** 'USR$...', 'USER', 'USERGROUP' should be constants or come from a configuration for maintainability.
- **Close Session Loop Logic:** The loop logic seems to decrement an index based on the initial length of `req.body`, but manipulates it as if `req.body` were modified within the loop.
- **Error Propagation:** Instead of returning `error.message`, consider sanitizing error responses to avoid leaking sensitive information.
- **Unused Commented Code:** Large blocks of commented-out code should be removed if not needed.
- **Potential Empty Request Body Handling:** No check for empty body before mapping over `req.body` for the creation of queries.
- **No Input Sanitization:** Inputs such as `REQUIRED_2FA`, `USER`, and `USERGROUP` are not validated or sanitized before use.
- **`startTransaction`:** The destructured transaction objects are assigned but there's no indication of how they're used in this patch.
- **No Schema Usage:** An empty `_schema` object is created but never used.

#### Improvements
- Un-comment and ensure proper validation of inputs, especially for `id` and elements of `req.body`.
- Consider implementing input sanitization mechanisms to prevent SQL injection.
- Replace 'magic strings' with properly named constants to enhance readability and maintainability.
- Avoid commenting out large blocks of code when submitting the final version; remove or refactor unused code.
- Ensure errors are handled uniformly and sensitive details are not sent to clients.
- Improve error handling in async operations, including transaction rollbacks in case of failure.
- Confirm the necessity of `_schema` or remove it if it's unused.


Quality Rate: 3/10

2024-01-29 17:41 UTC, hirurg-lybitel commented on libs/config/src/lib/config.ts
> +const origin = `https://${host}:${appPort}`;
лишний файл

2024-01-29 17:41 UTC, hirurg-lybitel commented on apps/gdmn-nxt-web/src/app/const.ts
лишний файл

2024-01-29 17:42 UTC, hirurg-lybitel commented on libs/config/src/lib/config.ts
лишний файл

2024-01-29 17:48 UTC, hirurg-lybitel requested changes
1. Ошибки в консоле 
![image](https://github.com/gsbelarus/gdmn-nxt/assets/11502258/7c97d5aa-93f4-41d9-a5c8-4cc05fed1a37)

2. Это что ли на 10 пользователей надо будет 10 отдельных инпутов?
![image](https://github.com/gsbelarus/gdmn-nxt/assets/11502258/b4e00d31-762f-402e-87dc-7f60c2cae51a)

Тут не надо ничего выдумывать. У нас есть компонент для множественного выбора. Просто его и использовать

2024-02-05 15:04 UTC, hirurg-lybitel commented on libs/config/src/lib/config.ts
не испрвалено, всё ещё этот лишний файл здесь присутсвует

2024-02-05 15:05 UTC, hirurg-lybitel commented on apps/gdmn-nxt-web/src/app/const.ts
не исправлено

2024-02-05 19:28 UTC, sashazernin commented
> * У нас во всём приложении при множественном выборе есть чекбоксы для удобства. Непонятно, почему здесь иначе
> * не надо закрывать список при выбор одного пользователя. Так очень неудобно выбирать несколько людей
>   ![image](https://private-user-images.githubusercontent.com/11502258/302334689-eb32f6f6-6ed5-4a2e-a7f7-2124f6c8d341.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxNTcyMzgsIm5iZiI6MTcwNzE1NjkzOCwicGF0aCI6Ii8xMTUwMjI1OC8zMDIzMzQ2ODktZWIzMmY2ZjYtNmVkNS00YTJlLWE3ZjctMjEyNGY2YzhkMzQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDE4MTUzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyZjAxNmQ2ZTcwN2FmZjlhYmVjODQxYzk5ZjU0NDAzYTdmODQyYjk1ZTBkOTEyMWU1NGYzNjYyMDY5YzQzNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ki11363u7enO5POBpQIC6gfyFA2iQ8ITiEgbMiNSZVw)

брал как приер автокомплит с сделок там он такой

2024-02-06 09:01 UTC, hirurg-lybitel commented
> > * У нас во всём приложении при множественном выборе есть чекбоксы для удобства. Непонятно, почему здесь иначе
> > * не надо закрывать список при выбор одного пользователя. Так очень неудобно выбирать несколько людей
> >   ![image](https://private-user-images.githubusercontent.com/11502258/302334689-eb32f6f6-6ed5-4a2e-a7f7-2124f6c8d341.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxNTcyMzgsIm5iZiI6MTcwNzE1NjkzOCwicGF0aCI6Ii8xMTUwMjI1OC8zMDIzMzQ2ODktZWIzMmY2ZjYtNmVkNS00YTJlLWE3ZjctMjEyNGY2YzhkMzQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDE4MTUzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyZjAxNmQ2ZTcwN2FmZjlhYmVjODQxYzk5ZjU0NDAzYTdmODQyYjk1ZTBkOTEyMWU1NGYzNjYyMDY5YzQzNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ki11363u7enO5POBpQIC6gfyFA2iQ8ITiEgbMiNSZVw)
> 
> брал как приер автокомплит с сделок там он такой

Их там много. О каком конкретно ты говоришь?

2024-02-06 11:02 UTC, sashazernin commented
> > > * У нас во всём приложении при множественном выборе есть чекбоксы для удобства. Непонятно, почему здесь иначе
> > > * не надо закрывать список при выбор одного пользователя. Так очень неудобно выбирать несколько людей
> > >   ![image](https://private-user-images.githubusercontent.com/11502258/302334689-eb32f6f6-6ed5-4a2e-a7f7-2124f6c8d341.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxNTcyMzgsIm5iZiI6MTcwNzE1NjkzOCwicGF0aCI6Ii8xMTUwMjI1OC8zMDIzMzQ2ODktZWIzMmY2ZjYtNmVkNS00YTJlLWE3ZjctMjEyNGY2YzhkMzQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDE4MTUzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyZjAxNmQ2ZTcwN2FmZjlhYmVjODQxYzk5ZjU0NDAzYTdmODQyYjk1ZTBkOTEyMWU1NGYzNjYyMDY5YzQzNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ki11363u7enO5POBpQIC6gfyFA2iQ8ITiEgbMiNSZVw)
> > 
> > 
> > брал как приер автокомплит с сделок там он такой
> 
> Их там много. О каком конкретно ты говоришь? Надо и там исправить будет возможно

клиенты

2024-02-06 11:45 UTC, hirurg-lybitel commented
> > > > * У нас во всём приложении при множественном выборе есть чекбоксы для удобства. Непонятно, почему здесь иначе
> > > > * не надо закрывать список при выбор одного пользователя. Так очень неудобно выбирать несколько людей
> > > >   ![image](https://private-user-images.githubusercontent.com/11502258/302334689-eb32f6f6-6ed5-4a2e-a7f7-2124f6c8d341.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxNTcyMzgsIm5iZiI6MTcwNzE1NjkzOCwicGF0aCI6Ii8xMTUwMjI1OC8zMDIzMzQ2ODktZWIzMmY2ZjYtNmVkNS00YTJlLWE3ZjctMjEyNGY2YzhkMzQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDE4MTUzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyZjAxNmQ2ZTcwN2FmZjlhYmVjODQxYzk5ZjU0NDAzYTdmODQyYjk1ZTBkOTEyMWU1NGYzNjYyMDY5YzQzNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ki11363u7enO5POBpQIC6gfyFA2iQ8ITiEgbMiNSZVw)
> > > 
> > > 
> > > брал как приер автокомплит с сделок там он такой
> > 
> > 
> > Их там много. О каком конкретно ты говоришь? Надо и там исправить будет возможно
> 
> клиент

и где там множественный выбор?

2024-02-06 11:47 UTC, sashazernin commented
> > клиент
> 
> и где там множественный выбор?

можественного нет, просто как пример брал.

2024-02-06 13:50 UTC, hirurg-lybitel requested changes
Это уже не смешно.

- нажал Добавить пользователя 
- никого не выбрал и нажал Сохранить
- подтвердил, что хочу сохранить 
- ничего не происходит 

в очередной раз напоминаю: ТЕСТИРОВАНИЕ

2024-02-07 17:22 UTC, merged