messenger input
gsbelarus/gdmn-nxt pull request #479
Opened 2024-01-14 13:10 UTC by sashazernin

#478

2024-01-14 21:40 UTC, hirurg-lybitel requested changes
В целом всё хорошо, но есть несколько замечаний.

1. Если копипастишь, то переименовывай названия. В коде фигурирует много названий с TelInput и других, не связанных с данным компонентом

2. По дизайну я немного иначе описал в задании. 
![image](https://github.com/gsbelarus/gdmn-nxt/assets/11502258/6ac424f0-a944-435b-83c2-d520f180308b)


- зачем такой большой отступ (1)? 
- зачем такой огромный выпадающий список с отступами (2)?
- добавь вертикальный разделитель между типом и юзернеймом, как в телефонном инпуте
- добавь стрелочку выпадающего списка, как делали в метках

2024-01-14 21:40 UTC, hirurg-lybitel commented on apps/gdmn-nxt-web/src/app/components/social-media-input/components/social-media-button/social-media-button.tsx
> +  socialName: string | null
Если это просто строка будет, то можно передать что-угодно тогда. Должен ограниченный набор возможных вариантов быть. И значение по умолчанию тоже не помешает

2024-01-14 21:40 UTC, hirurg-lybitel commented on apps/gdmn-nxt-web/src/app/components/social-media-input/components/social-media-button/social-media-button.tsx
> +  isFlagsMenuOpened: boolean;
о каких флагах идёт речь?

2024-01-14 21:40 UTC, hirurg-lybitel commented on apps/gdmn-nxt-web/src/app/components/social-media-input/components/social-media-button/social-media-button.tsx
> +  fixedCode?: boolean;
о каком коде идёт речь? Где это используется?

2024-01-14 21:40 UTC, hirurg-lybitel commented on apps/gdmn-nxt-web/src/app/components/social-media-input/index.tsx
> +  disableFormatting?: boolean;
о каком форматирвоании идёт речь?

2024-01-14 21:40 UTC, hirurg-lybitel commented on apps/gdmn-nxt-web/src/app/const.ts
зачем этот файл здесь?

2024-01-14 21:40 UTC, hirurg-lybitel commented on libs/config/src/lib/config.ts
зачем этот файл здесь?

2024-01-14 21:40 UTC, hirurg-lybitel commented on yarn.lock
что в ярнлоке изменилось? 
ты же не добавлял ничего нового

2024-01-14 21:40 UTC, hirurg-lybitel commented on apps/gdmn-nxt-web/src/app/customers/customer-edit/customer-edit.tsx
зачем этот файл здесь?

2024-01-15 15:36 UTC, sashazernin commented
я же не добавлял эти файлы
![image](https://github.com/gsbelarus/gdmn-nxt/assets/94962537/9a801729-2bfe-4c34-b5aa-23cde6b8e3ae)

2024-01-15 15:36 UTC, sashazernin commented on yarn.lock
не знаю постоянно когда yarn прописываю лок файл меняется

2024-01-15 16:00 UTC, hirurg-lybitel commented
> я же не добавлял эти файлы ![image](https://private-user-images.githubusercontent.com/94962537/296801648-9a801729-2bfe-4c34-b5aa-23cde6b8e3ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMzQ0ODYsIm5iZiI6MTcwNTMzNDE4NiwicGF0aCI6Ii85NDk2MjUzNy8yOTY4MDE2NDgtOWE4MDE3MjktMmJmZS00YzM0LWI1YWEtMjNjZGU2YjhlM2FlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDE1NTYyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2NDVlODJjZjNmMmM2NDQ1ZTI2MDc4NDQyMjM2NTQyNjBkMjAyZDgxZDUzMzM3ODUyNzg0NGM1YzExYTkxZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lBbotYNL3SCyXCIxHJQ_UZqObC5Nyt-X3PifM_JweAQ)

как не добавлял, если они в списке изменённых тобой файлов?

2024-01-15 17:00 UTC, sashazernin commented
> > я же не добавлял эти файлы ![image](https://private-user-images.githubusercontent.com/94962537/296801648-9a801729-2bfe-4c34-b5aa-23cde6b8e3ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMzQ0ODYsIm5iZiI6MTcwNTMzNDE4NiwicGF0aCI6Ii85NDk2MjUzNy8yOTY4MDE2NDgtOWE4MDE3MjktMmJmZS00YzM0LWI1YWEtMjNjZGU2YjhlM2FlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDE1NTYyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2NDVlODJjZjNmMmM2NDQ1ZTI2MDc4NDQyMjM2NTQyNjBkMjAyZDgxZDUzMzM3ODUyNzg0NGM1YzExYTkxZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lBbotYNL3SCyXCIxHJQ_UZqObC5Nyt-X3PifM_JweAQ)
> 
> как не добавлял, если они в списке изменённых тобой файлов?

а это чтобы проект запустить там данные для итоговой версии, а в клиентах забыл импорт убрать

2024-01-16 11:48 UTC, hirurg-lybitel commented
> > > я же не добавлял эти файлы ![image](https://private-user-images.githubusercontent.com/94962537/296801648-9a801729-2bfe-4c34-b5aa-23cde6b8e3ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMzQ0ODYsIm5iZiI6MTcwNTMzNDE4NiwicGF0aCI6Ii85NDk2MjUzNy8yOTY4MDE2NDgtOWE4MDE3MjktMmJmZS00YzM0LWI1YWEtMjNjZGU2YjhlM2FlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDE1NTYyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2NDVlODJjZjNmMmM2NDQ1ZTI2MDc4NDQyMjM2NTQyNjBkMjAyZDgxZDUzMzM3ODUyNzg0NGM1YzExYTkxZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lBbotYNL3SCyXCIxHJQ_UZqObC5Nyt-X3PifM_JweAQ)
> > 
> > 
> > как не добавлял, если они в списке изменённых тобой файлов?
> 
> а это чтобы проект запустить там данные для итоговой версии, а в клиентах забыл импорт убрать

так там наоборот изменённые файлы, которые сломают итоговую версию

2024-01-16 11:51 UTC, sashazernin commented
> > > > я же не добавлял эти файлы ![image](https://private-user-images.githubusercontent.com/94962537/296801648-9a801729-2bfe-4c34-b5aa-23cde6b8e3ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMzQ0ODYsIm5iZiI6MTcwNTMzNDE4NiwicGF0aCI6Ii85NDk2MjUzNy8yOTY4MDE2NDgtOWE4MDE3MjktMmJmZS00YzM0LWI1YWEtMjNjZGU2YjhlM2FlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDE1NTYyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2NDVlODJjZjNmMmM2NDQ1ZTI2MDc4NDQyMjM2NTQyNjBkMjAyZDgxZDUzMzM3ODUyNzg0NGM1YzExYTkxZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lBbotYNL3SCyXCIxHJQ_UZqObC5Nyt-X3PifM_JweAQ)
> > > 
> > > 
> > > как не добавлял, если они в списке изменённых тобой файлов?
> > 
> > 
> > а это чтобы проект запустить там данные для итоговой версии, а в клиентах забыл импорт убрать
> 
> так там наоборот изменённые файлы, которые сломают итоговую версию, если слить ветки

испрвил

2024-01-16 11:54 UTC, sashazernin commented
ревертнишь ярн лок сам? я не знаю как.

2024-01-16 11:59 UTC, hirurg-lybitel commented
> @hirurg-lybitel ревертнишь ярн лок сам? я не знаю как.

Чёрт с ним, пересоберу. Остальное только убери ненужное.

2024-01-16 12:12 UTC, hirurg-lybitel commented on apps/gdmn-nxt-web/src/app/components/social-media-input/components/social-media-button/social-media-button.tsx
> +          className="TelInput-IconButton"
До сих пор скопипастенные названия

2024-01-16 12:12 UTC, hirurg-lybitel commented on apps/gdmn-nxt-web/src/app/components/social-media-input/components/social-media-item/social-media-menu-item.tsx
> +      <Styled.ListItemIcon className="TelInput-ListItemIcon-flag">
До сих пор скопипастенные названия

2024-01-16 12:12 UTC, hirurg-lybitel commented on apps/gdmn-nxt-web/src/app/components/social-media-input/components/social-media-menu/social-media-menu.tsx
> +      className={`TelInput-Menu ${className ?? ''}`}
До сих пор скопипастенные названия

2024-01-16 12:13 UTC, hirurg-lybitel commented on apps/gdmn-nxt-web/src/app/components/social-media-input/index.tsx
> +        type="tel"
почему здесть тип tel?

2024-01-16 12:13 UTC, hirurg-lybitel reviewed
И ещё кое-что

2024-01-17 11:31 UTC, hirurg-lybitel requested changes
блин, просто не понимаю этой тяги к пустым пространствам и игнорирования просьбы добавить простой вертикальный разделитель

![image](https://github.com/gsbelarus/gdmn-nxt/assets/11502258/dfc070f3-f5bc-4cbe-9b5a-dbc501b054fd)

2024-01-17 11:32 UTC, hirurg-lybitel commented
> блин, просто не понимаю этой тяги к пустым пространствам и игнорирования просьбы добавить простой вертикальный разделитель
> 
> ![image](https://private-user-images.githubusercontent.com/11502258/297364166-dfc070f3-f5bc-4cbe-9b5a-dbc501b054fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0OTEzODIsIm5iZiI6MTcwNTQ5MTA4MiwicGF0aCI6Ii8xMTUwMjI1OC8yOTczNjQxNjYtZGZjMDcwZjMtZjViYy00Y2JlLTliNWEtZGJjNTAxYjA1NGZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDExMzEyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1YjFkYWM5M2ZlNTAxYjc1MWY3NjA3N2EzNDA2NzM2Njc1NmVjY2Y5MDZjN2QxNmY5ZWJjYzRlNDUyZmNiYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d8yRfCUAletw9L6yhaLC_DAQRIvqvoBDyNLW1ICuE2Q)

Уже сам доделаю, т.к. компонент нужен поскорее этот

2024-01-17 11:32 UTC, sashazernin commented
> блин, просто не понимаю этой тяги к пустым пространствам и игнорирования просьбы добавить простой вертикальный разделитель
> 
> ![image](https://private-user-images.githubusercontent.com/11502258/297364166-dfc070f3-f5bc-4cbe-9b5a-dbc501b054fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0OTE0MTEsIm5iZiI6MTcwNTQ5MTExMSwicGF0aCI6Ii8xMTUwMjI1OC8yOTczNjQxNjYtZGZjMDcwZjMtZjViYy00Y2JlLTliNWEtZGJjNTAxYjA1NGZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDExMzE1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyMTljNDMzNDZkNjM1NWVkNGI4MDdkMTUxYjFhOWYwNWFjZjllYmZjOTU1MzI1YTE5MGJmOTg3NjdhMWM3Y2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f-mqtZ739WE0rZFr78VrO0iTDXYuxhLsQ4rG4_qYuj0)

добавил же разделитель

2024-01-17 11:50 UTC, hirurg-lybitel commented
> > блин, просто не понимаю этой тяги к пустым пространствам и игнорирования просьбы добавить простой вертикальный разделитель
> > ![image](https://private-user-images.githubusercontent.com/11502258/297364166-dfc070f3-f5bc-4cbe-9b5a-dbc501b054fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0OTE0MTEsIm5iZiI6MTcwNTQ5MTExMSwicGF0aCI6Ii8xMTUwMjI1OC8yOTczNjQxNjYtZGZjMDcwZjMtZjViYy00Y2JlLTliNWEtZGJjNTAxYjA1NGZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDExMzE1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyMTljNDMzNDZkNjM1NWVkNGI4MDdkMTUxYjFhOWYwNWFjZjllYmZjOTU1MzI1YTE5MGJmOTg3NjdhMWM3Y2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f-mqtZ739WE0rZFr78VrO0iTDXYuxhLsQ4rG4_qYuj0)
> 
> добавил же разделитель, при переключении на тг он будет

так а почему только для тг?

2024-01-17 11:59 UTC, merged