feat: adding cjntacts to cliend
gsbelarus/gdmn-nxt pull request #503
Opened 2024-02-01 11:58 UTC by sashazernin

#492

2024-02-01 13:16 UTC, hirurg-lybitel requested changes
проект просто не запускается 

![image](https://github.com/gsbelarus/gdmn-nxt/assets/11502258/d367a32e-087e-4b68-ac2d-21bab213111a)

2024-02-01 13:44 UTC, sashazernin commented
> проект просто не запускается
> 
> ![image](https://private-user-images.githubusercontent.com/11502258/301515994-d367a32e-087e-4b68-ac2d-21bab213111a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3OTM2OTgsIm5iZiI6MTcwNjc5MzM5OCwicGF0aCI6Ii8xMTUwMjI1OC8zMDE1MTU5OTQtZDM2N2EzMmUtMDg3ZS00YjY4LWFjMmQtMjFiYWIyMTMxMTFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDEzMTYzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxNWY4ZWYxMjdmNDk4NGYyYTU5MjhiZTU3MWY2NzAyMTdkN2I0ZTgyNjllZDkwMWRhYWU1MjNkZDM0NjAyN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CHxNqLBYSq79TZmdG5xthYKh0meufX_7VXuAE4-ouf4)

пофиксил

2024-02-01 13:53 UTC, hirurg-lybitel requested changes
Максимально сырой результат вышел

![image](https://github.com/gsbelarus/gdmn-nxt/assets/11502258/76d7e9ab-a011-463b-bd58-17636d79b2cb)

- отступов нет
- каких "калиента"? Мы контакты выбираем
- из-за того, что ты отображаешь сразу все тысячи контактов, всё очень медленно работает 
- кнопка отмена не работает
- при добавлении контактов ничего не отображается в таблице контактов, только после ручного обновления

2024-02-02 18:49 UTC, hirurg-lybitel requested changes
Вижу, что ты вообще не тестируешь ничего

Выбрал контакты, отменил, добавляю заново, все, ранее выбранные, остались 
https://github.com/gsbelarus/gdmn-nxt/assets/11502258/2e8f1387-a21c-42ea-8e4f-579cf38908a4

2024-02-05 00:38 UTC, sashazernin commented
> Вижу, что ты вообще не тестируешь ничего
> 
> Выбрал контакты, отменил, добавляю заново, все, ранее выбранные, остались https://github.com/gsbelarus/gdmn-nxt/assets/11502258/2e8f1387-a21c-42ea-8e4f-579cf38908a4

ну да это почти не тестировал, долго делал хотелось поскорее закончить

2024-02-05 10:07 UTC, hirurg-lybitel commented
Слишком долго это задача делалась. Уже переделали полностью окно редактирования клиентов за это время и попутно реализовали и этот функционал добавления

2024-02-05 10:07 UTC, closed without merging