fix: close contact email edit on blur
gsbelarus/gdmn-nxt pull request #511
Opened 2024-02-04 23:38 UTC by sashazernin

#495

2024-02-05 14:49 UTC, hirurg-lybitel requested changes
мерж не в ту ветку

2024-02-05 14:55 UTC, hirurg-lybitel commented
> мерж не в ту ветку

исправил

2024-02-06 14:00 UTC, hirurg-lybitel submitted a review, later dismissed
Сливать пока не будем, т.к. изначальная задача расширилась

2024-02-06 17:47 UTC, sashazernin commented
> Сливать пока не будем, т.к. изначальная задача расширилась

ну я уже описанные изменения внес

2024-02-06 20:42 UTC, hirurg-lybitel requested changes
так не работает же

![image](https://github.com/gsbelarus/gdmn-nxt/assets/11502258/88db2724-892c-4497-9469-0ec6b452f345)

2024-02-06 20:43 UTC, sashazernin commented
я делал только для поля почты, для остальных тоже самое сделать?

2024-02-06 21:15 UTC, hirurg-lybitel commented
> я делал только для поля почты, для остальных тоже самое сделать?

почему только для почты?
да, в задании про все инпуты сказано

2024-02-06 21:17 UTC, sashazernin commented
> > я делал только для поля почты, для остальных тоже самое сделать?
> 
> почему только для почты? да, в задании про все инпуты сказано

щас сделаю для всех

2024-02-09 22:15 UTC, hirurg-lybitel requested changes
Снова недотестировал

Невозможно поменять тип мессендежра

2024-02-13 08:25 UTC, sashazernin commented
> Снова недотестировал
> 
> Невозможно поменять тип мессендежра

даже самому интересно как я это пропустил

2024-02-13 19:34 UTC, hirurg-lybitel requested changes
- добавить мессенджер
- открыть список
- ничего не выбрав, нажать на поле вода имя пользователя (передумал менять тип)
- всё исчезло ❌

2024-02-14 10:08 UTC, hirurg-lybitel requested changes
Ох, ну ты и понаписывал тут.
Вроде уже всё работает без проблем, но до чего же сложно реализовано.

Попробую сам сделать

2024-02-14 10:10 UTC, sashazernin commented
> Ох, ну ты и понаписывал тут. Вроде уже всё работает без проблем, но до чего же сложно реализовано.
> 
> Попробую сам сделать

ну я просто не знаю как иначе сделать, если сможешь реализовать проще будет просто чудесно гляну потом как сделал возьму на заметку

2024-02-14 12:08 UTC, closed without merging