fix: the height of the list row
gsbelarus/gdmn-nxt pull request #528
Opened 2024-02-15 12:31 UTC by sashazernin

#521

2024-02-15 13:00 UTC, hirurg-lybitel requested changes
Это не решение программиста, а костыль обычный

Во-первых, мы используем один грид для всех, так что его настраивать и надо, а не одну его имплементацию. В текущем решении подобные настройки придётся делать везде, где грид используется

Во-вторых, что будет, если просто поменяем высоту строки в какой-нибудь одной имплементации? А ничего, твоё решение жёстко фиксирует выcоту около 40px

Решение должно быть динамическим, а не линеечкой отмерять желаемый результат на экране

2024-02-15 13:19 UTC, hirurg-lybitel commented
> > Это не решение программиста, а костыль обычный
> > Во-первых, мы используем один грид для всех, так что его настраивать и надо, а не одну его имплементацию. В текущем решении подобные настройки придётся делать везде, где грид используется
> > Во-вторых, что будет, если просто поменяем высоту строки в какой-нибудь одной имплементации? А ничего, твоё решение жёстко фиксирует выcоту около 40px
> > Решение должно быть динамическим, а не линеечкой отмерять желаемый результат на экране
> 
> ну иначе надо как то проверять влазят ли метки в строку, есть идеи как это лучше реализовать?

У тебя есть конечная высота (динамическая), которая должна получиться. От этого и исходить

2024-02-15 15:43 UTC, sashazernin commented
> > > Это не решение программиста, а костыль обычный
> > > Во-первых, мы используем один грид для всех, так что его настраивать и надо, а не одну его имплементацию. В текущем решении подобные настройки придётся делать везде, где грид используется
> > > Во-вторых, что будет, если просто поменяем высоту строки в какой-нибудь одной имплементации? А ничего, твоё решение жёстко фиксирует выcоту около 40px
> > > Решение должно быть динамическим, а не линеечкой отмерять желаемый результат на экране
> > 
> > 
> > ну иначе надо как то проверять влазят ли метки в строку, есть идеи как это лучше реализовать?
> 
> У тебя есть конечная высота (динамическая), которая должна получиться. От этого и исходить

а как мне эту высоту получить? т.е берем высоту которая получилась если она меньше чем при переносе метки то уменьшаем до 40?

2024-02-15 20:58 UTC, hirurg-lybitel commented
> > > > Это не решение программиста, а костыль обычный
> > > > Во-первых, мы используем один грид для всех, так что его настраивать и надо, а не одну его имплементацию. В текущем решении подобные настройки придётся делать везде, где грид используется
> > > > Во-вторых, что будет, если просто поменяем высоту строки в какой-нибудь одной имплементации? А ничего, твоё решение жёстко фиксирует выcоту около 40px
> > > > Решение должно быть динамическим, а не линеечкой отмерять желаемый результат на экране
> > > 
> > > 
> > > ну иначе надо как то проверять влазят ли метки в строку, есть идеи как это лучше реализовать?
> > 
> > 
> > У тебя есть конечная высота (динамическая), которая должна получиться. От этого и исходить
> 
> а как мне эту высоту получить? т.е берем высоту которая получилась если она меньше чем при переносе метки то уменьшаем до 40? Не проще ли настроить отступы внутри строки? если отступы будут маленькие то строки на всех гридах будут автоматически минимальной высоты

Высота строки или передаётся параметром, или берётся из константы, если параметром не установлена.
Зная конечный результат, рассчитать значения или отступов, или чего-угодно другого в css не должно быть проблемой

2024-02-16 09:11 UTC, sashazernin commented
> > > > > Это не решение программиста, а костыль обычный
> > > > > Во-первых, мы используем один грид для всех, так что его настраивать и надо, а не одну его имплементацию. В текущем решении подобные настройки придётся делать везде, где грид используется
> > > > > Во-вторых, что будет, если просто поменяем высоту строки в какой-нибудь одной имплементации? А ничего, твоё решение жёстко фиксирует выcоту около 40px
> > > > > Решение должно быть динамическим, а не линеечкой отмерять желаемый результат на экране
> > > > 
> > > > 
> > > > ну иначе надо как то проверять влазят ли метки в строку, есть идеи как это лучше реализовать?
> > > 
> > > 
> > > У тебя есть конечная высота (динамическая), которая должна получиться. От этого и исходить
> > 
> > 
> > а как мне эту высоту получить? т.е берем высоту которая получилась если она меньше чем при переносе метки то уменьшаем до 40? Не проще ли настроить отступы внутри строки? если отступы будут маленькие то строки на всех гридах будут автоматически минимальной высоты
> 
> Высота строки или передаётся параметром, или берётся из константы, если параметром не установлена. Зная конечный результат, рассчитать значения или отступов, или чего-угодно другого в css не должно быть проблемой

ну сейчас высота динамически задается, но когда нет переноса меток надо чтобы она была равна 40, так а как я узнаю что метки не перенеслись но новую строку? способа получить текущую высоту строки, после ее динамического определения, я не нашел.

2024-02-16 16:14 UTC, merged