Migration for mui v5   v6
gsbelarus/gdmn-nxt pull request #530
Opened 2024-02-20 16:12 UTC by sashazernin

2024-02-20 17:06 UTC, sashazernin commented on apps/gdmn-nxt-web/src/app/pages/Dashboard/dashboard/dashboard.tsx
> +                          value={undefined}
Не понимаю почему бесконечный ререндер если указать период

2024-02-20 17:08 UTC, sashazernin commented on apps/gdmn-nxt-web/src/app/components/Kanban/kanban-list/custom-grid-tree-data-grouping-cell.tsx
> +              {(rowNode as any).childrenExpanded ? <KeyboardArrowDownIcon /> : <KeyboardArrowRightIcon />}
в подобных этому местах что то с типом, ругается на то что нету свойства childrenExpanded

2024-02-21 17:43 UTC, hirurg-lybitel reviewed
не запускается 

![image](https://github.com/gsbelarus/gdmn-nxt/assets/11502258/319c258b-ba34-4369-8849-dc29c063f39a)

2024-02-21 19:38 UTC, sashazernin commented
> не запускается
> 
> ![image](https://private-user-images.githubusercontent.com/11502258/306721311-319c258b-ba34-4369-8849-dc29c063f39a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1NDQ0OTQsIm5iZiI6MTcwODU0NDE5NCwicGF0aCI6Ii8xMTUwMjI1OC8zMDY3MjEzMTEtMzE5YzI1OGItYmEzNC00MzY5LTg4NDktZGMyOWMwNjNmMzlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDE5MzYzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyZDU2YjZlMjY0OTk5YzA5Y2ZmMTAyZjEzMmQ3MWJkNWUxYTVmYzdkNzk3YTVjZmNhY2MzZTNlMDkwZGIzOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sGePMCLKTglSGVwTebnhRWavSGcZu8l3uNNDVHGaqXQ)

странно я это давно исправил, у меня это все исправлено не знаю почему у тебя нет, попробуй подгрузить изменения.

2024-02-21 20:23 UTC, hirurg-lybitel commented
> > не запускается
> > ![image](https://private-user-images.githubusercontent.com/11502258/306721311-319c258b-ba34-4369-8849-dc29c063f39a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1NDQ0OTQsIm5iZiI6MTcwODU0NDE5NCwicGF0aCI6Ii8xMTUwMjI1OC8zMDY3MjEzMTEtMzE5YzI1OGItYmEzNC00MzY5LTg4NDktZGMyOWMwNjNmMzlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDE5MzYzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyZDU2YjZlMjY0OTk5YzA5Y2ZmMTAyZjEzMmQ3MWJkNWUxYTVmYzdkNzk3YTVjZmNhY2MzZTNlMDkwZGIzOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sGePMCLKTglSGVwTebnhRWavSGcZu8l3uNNDVHGaqXQ)
> 
> странно я это давно исправил, у меня все нормально не знаю почему у тебя нет, попробуй подгрузить изменения.

да, мой косяк, плохо обновил

2024-02-21 20:28 UTC, hirurg-lybitel commented
ты проверял?

все гриды стали растягиваться на всё количество строк

2024-02-21 20:36 UTC, hirurg-lybitel commented on apps/gdmn-nxt-web/src/app/components/Kanban/kanban-list/custom-grid-tree-data-grouping-cell.tsx
> +              {(rowNode as any).childrenExpanded ? <KeyboardArrowDownIcon /> : <KeyboardArrowRightIcon />}
так а в новой документции вообще используется этот подход для группировки?

2024-02-21 20:42 UTC, hirurg-lybitel commented on apps/gdmn-nxt-web/src/app/pages/Dashboard/dashboard/dashboard.tsx
> +                          value={undefined}
мы переходили на новую версию, чтобы использовать новые компоненты.
в новой версии появился компонент Date Range Calendar. Вот его и попробуй использовать

2024-02-22 13:27 UTC, sashazernin commented
> ты проверял?
> 
> первое, что бросается в глаза: все гриды стали растягиваться на всё количество строк

ну проверял но не слишком тщательно первое что заметил пофиксил

2024-02-22 17:14 UTC, sashazernin commented
@hirurg-lybitel не вижу где что растягивается

2024-02-22 21:23 UTC, sashazernin commented on apps/gdmn-nxt-web/src/app/pages/Dashboard/dashboard/dashboard.tsx
> +                          value={undefined}
теперь все нормально работает но пришлось any прописать потому что там типо что то просит [dayjs, dayjs] но по факту принимает [Date, Date] и ругается на неправильную дату если dayjs передавать

2024-02-22 21:29 UTC, sashazernin commented on apps/gdmn-nxt-web/src/app/components/Kanban/kanban-list/custom-grid-tree-data-grouping-cell.tsx
> +              {(rowNode as any).childrenExpanded ? <KeyboardArrowDownIcon /> : <KeyboardArrowRightIcon />}
этого не знаю

2024-02-23 08:10 UTC, hirurg-lybitel commented
Как на рабочей версии
![image](https://github.com/gsbelarus/gdmn-nxt/assets/11502258/d17494bb-bc9b-45d7-b809-99fab6bdf110)

как на текущей версии
![image](https://github.com/gsbelarus/gdmn-nxt/assets/11502258/65782d1c-6a80-4089-9b40-81da28cb13cb)

2024-02-26 17:00 UTC, sashazernin commented
> Как на рабочей версии ![image](https://private-user-images.githubusercontent.com/11502258/307257593-eb3aef8a-c960-450e-a92b-9dc382c7298d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5NjcwODksIm5iZiI6MTcwODk2Njc4OSwicGF0aCI6Ii8xMTUwMjI1OC8zMDcyNTc1OTMtZWIzYWVmOGEtYzk2MC00NTBlLWE5MmItOWRjMzgyYzcyOThkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDE2NTk0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlNjkyNDg5MzEwY2ZhZThkMzY2MzdlZjZlMjBlZWM2YjRhODk5Y2Q5OGJhNTExM2U2YzEwY2NjYjJmNWVmOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gIN5s2uQOGJfqD5mZ0FVM0Mnu6AAi3qCpYgTgXFQ4Do)
> 
> как на текущей версии ![image](https://private-user-images.githubusercontent.com/11502258/307257491-3819c2a4-478e-40e0-bf6b-6bcb5e86992f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5NjcwODksIm5iZiI6MTcwODk2Njc4OSwicGF0aCI6Ii8xMTUwMjI1OC8zMDcyNTc0OTEtMzgxOWMyYTQtNDc4ZS00MGUwLWJmNmItNmJjYjVlODY5OTJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDE2NTk0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwNDI2MDIyYjQ2NDhlYmUxYmJmYWM0MjA1YzkzMzNhNzk0MzA0MzY5Y2E5NTM1YmVhZTVjNTFmOWM5MjhmNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F_jUKWvDlpap56RZQFUgnZDNdhkE5RII0WGHyO95ZFE)

![image](https://github.com/gsbelarus/gdmn-nxt/assets/94962537/42a3fa55-a7c9-4de9-ac6d-a164b409d9b7)
у меня почему то все нормально

2024-02-27 01:29 UTC, hirurg-lybitel commented
> > Как на рабочей версии ![image](https://private-user-images.githubusercontent.com/11502258/307257593-eb3aef8a-c960-450e-a92b-9dc382c7298d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5NjcwODksIm5iZiI6MTcwODk2Njc4OSwicGF0aCI6Ii8xMTUwMjI1OC8zMDcyNTc1OTMtZWIzYWVmOGEtYzk2MC00NTBlLWE5MmItOWRjMzgyYzcyOThkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDE2NTk0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlNjkyNDg5MzEwY2ZhZThkMzY2MzdlZjZlMjBlZWM2YjRhODk5Y2Q5OGJhNTExM2U2YzEwY2NjYjJmNWVmOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gIN5s2uQOGJfqD5mZ0FVM0Mnu6AAi3qCpYgTgXFQ4Do)
> > как на текущей версии ![image](https://private-user-images.githubusercontent.com/11502258/307257491-3819c2a4-478e-40e0-bf6b-6bcb5e86992f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5NjcwODksIm5iZiI6MTcwODk2Njc4OSwicGF0aCI6Ii8xMTUwMjI1OC8zMDcyNTc0OTEtMzgxOWMyYTQtNDc4ZS00MGUwLWJmNmItNmJjYjVlODY5OTJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDE2NTk0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwNDI2MDIyYjQ2NDhlYmUxYmJmYWM0MjA1YzkzMzNhNzk0MzA0MzY5Y2E5NTM1YmVhZTVjNTFmOWM5MjhmNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F_jUKWvDlpap56RZQFUgnZDNdhkE5RII0WGHyO95ZFE)
> 
> ![image](https://private-user-images.githubusercontent.com/94962537/307878989-42a3fa55-a7c9-4de9-ac6d-a164b409d9b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5OTc2MTIsIm5iZiI6MTcwODk5NzMxMiwicGF0aCI6Ii85NDk2MjUzNy8zMDc4Nzg5ODktNDJhM2ZhNTUtYTdjOS00ZGU5LWFjNmQtYTE2NGI0MDlkOWI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDAxMjgzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkZTQ2YTk0NWU5MDMzYWNhNzYxYTU1ZjQyNTMwMGQ1YjFkMDczNzcxZGJhNTc2ODVkMzVmOWE1Mjk3M2I1ZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oUvXIxXV2bzS3Rg4_QQKeJAOqq_n3sjEdGDQ5_S9IR8) у меня почему то все нормально, но да там что то сделали с вычислением ширины видимо. Видно если менять размер окна браузера.

А в смысле "нормально"?
На твоём скрине такая же ситуация с убежавших футером грида

2024-02-27 13:40 UTC, sashazernin commented
> > > Как на рабочей версии ![image](https://private-user-images.githubusercontent.com/11502258/307257593-eb3aef8a-c960-450e-a92b-9dc382c7298d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5NjcwODksIm5iZiI6MTcwODk2Njc4OSwicGF0aCI6Ii8xMTUwMjI1OC8zMDcyNTc1OTMtZWIzYWVmOGEtYzk2MC00NTBlLWE5MmItOWRjMzgyYzcyOThkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDE2NTk0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlNjkyNDg5MzEwY2ZhZThkMzY2MzdlZjZlMjBlZWM2YjRhODk5Y2Q5OGJhNTExM2U2YzEwY2NjYjJmNWVmOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gIN5s2uQOGJfqD5mZ0FVM0Mnu6AAi3qCpYgTgXFQ4Do)
> > > как на текущей версии ![image](https://private-user-images.githubusercontent.com/11502258/307257491-3819c2a4-478e-40e0-bf6b-6bcb5e86992f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5NjcwODksIm5iZiI6MTcwODk2Njc4OSwicGF0aCI6Ii8xMTUwMjI1OC8zMDcyNTc0OTEtMzgxOWMyYTQtNDc4ZS00MGUwLWJmNmItNmJjYjVlODY5OTJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDE2NTk0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwNDI2MDIyYjQ2NDhlYmUxYmJmYWM0MjA1YzkzMzNhNzk0MzA0MzY5Y2E5NTM1YmVhZTVjNTFmOWM5MjhmNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F_jUKWvDlpap56RZQFUgnZDNdhkE5RII0WGHyO95ZFE)
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/94962537/307878989-42a3fa55-a7c9-4de9-ac6d-a164b409d9b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5OTc2MTIsIm5iZiI6MTcwODk5NzMxMiwicGF0aCI6Ii85NDk2MjUzNy8zMDc4Nzg5ODktNDJhM2ZhNTUtYTdjOS00ZGU5LWFjNmQtYTE2NGI0MDlkOWI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDAxMjgzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkZTQ2YTk0NWU5MDMzYWNhNzYxYTU1ZjQyNTMwMGQ1YjFkMDczNzcxZGJhNTc2ODVkMzVmOWE1Mjk3M2I1ZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oUvXIxXV2bzS3Rg4_QQKeJAOqq_n3sjEdGDQ5_S9IR8) у меня почему то все нормально, но да там что то сделали с вычислением ширины видимо. Видно если менять размер окна браузера.
> 
> А в смысле "нормально"? На твоём скрине такая же ситуация с убежавших футером грида

а это, щас исправлю не заметил

2024-03-13 14:43 UTC, hirurg-lybitel requested changes
1. Типы задач. Редактирование. Не работает (нет сохранения и закрытия)
2. Типы задач. Добавление. То же самое

2024-03-18 14:47 UTC, hirurg-lybitel commented on apps/gdmn-nxt-web/src/app/components/Kanban/kanban-list/custom-grid-tree-data-grouping-cell.tsx
> +              {(rowNode as any).childrenExpanded ? <KeyboardArrowDownIcon /> : <KeyboardArrowRightIcon />}
Не понимаю ответа. Так надо узнать

2024-03-18 14:50 UTC, hirurg-lybitel commented on apps/gdmn-nxt-server/src/main.ts
> +        const permissions = (await cacheManager.getKey('permissions')) ?? {};
Зачем все эти скобочки расставил повсюду?

2024-03-18 14:51 UTC, hirurg-lybitel requested changes
Всё хорошо, но я думал вопрос про `(rowNode as any).childrenExpanded` закрыт уже давно. Надо нормально сделать, как в примерах с группировкой

2024-03-21 12:22 UTC, hirurg-lybitel commented on apps/gdmn-nxt-server/src/main.ts
> +        const permissions = (await cacheManager.getKey('permissions')) ?? {};
а что с этим вопросом?

2024-03-21 13:14 UTC, merged