feat: arrow for documents
gsbelarus/gdmn-nxt pull request #551
Opened 2024-03-08 12:59 UTC by sashazernin

#544

2024-03-11 10:29 UTC, hirurg-lybitel requested changes
в очередной раз проигнорировано исходное задание и сделана лишь часть

2024-03-11 12:55 UTC, sashazernin commented
> в очередной раз проигнорировано исходное задание и сделана лишь часть

ой, да, забыл про отключение кнопки

2024-03-11 22:01 UTC, sashazernin commented
![image](https://github.com/gsbelarus/gdmn-nxt/assets/94962537/c2d773f6-1d33-4f99-85f3-ea2dfc776507)
я так понимаю тут нет никакого поля о наличии или количестве услуг, я его добавлю или как мне сделать?

2024-03-12 14:36 UTC, hirurg-lybitel commented
> ![image](https://private-user-images.githubusercontent.com/94962537/311876934-c2d773f6-1d33-4f99-85f3-ea2dfc776507.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNTQ0MDEsIm5iZiI6MTcxMDI1NDEwMSwicGF0aCI6Ii85NDk2MjUzNy8zMTE4NzY5MzQtYzJkNzczZjYtMWQzMy00Zjk5LTg1ZjMtZWEyZGZjNzc2NTA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDE0MzUwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlN2NhYjc1NTg4YjY4N2FmN2VjODhmYWE5M2VhNDg5ZDExMTJiZjU0YzE1MzM3OGVkMmQwZTcyZjM3MWRiM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T0IsLqng6i0WHhZ6hVTltzFM7kU5IZLTqN655Q_prjY) я так понимаю тут нет никакого поля о наличии или количестве услуг, я его добавлю или как мне сделать?

Не надо ничего добавлять. Всё необходимое уже есть. Данные отображаются при раскрытии панели же

2024-03-13 13:22 UTC, hirurg-lybitel commented on apps/gdmn-nxt-web/src/app/pages/Managment/contracts/columns.tsx
> +    <IconButton disabled={data.length <= 0 || isLoading}>
а как длина массива может быть меньше 0?

2024-03-13 13:24 UTC, merged

2024-03-13 13:31 UTC, sashazernin commented on apps/gdmn-nxt-web/src/app/pages/Managment/contracts/columns.tsx
> +    <IconButton disabled={data.length <= 0 || isLoading}>
ну если только указывать -1 или что то роде того по сути разницы большой нету между === и <=

2024-03-13 13:34 UTC, hirurg-lybitel commented on apps/gdmn-nxt-web/src/app/pages/Managment/contracts/columns.tsx
> +    <IconButton disabled={data.length <= 0 || isLoading}>
что такое -1 ?

2024-03-13 13:35 UTC, sashazernin commented on apps/gdmn-nxt-web/src/app/pages/Managment/contracts/columns.tsx
> +    <IconButton disabled={data.length <= 0 || isLoading}>
ну в этом случае -1 не может быть так что да логичнее === писать

2024-03-13 13:36 UTC, hirurg-lybitel commented on apps/gdmn-nxt-web/src/app/pages/Managment/contracts/columns.tsx
> +    <IconButton disabled={data.length <= 0 || isLoading}>
ты логику свою объясни, а не вопрос закрывай