fix: menu button is not active
gsbelarus/gdmn-nxt pull request #553
Opened 2024-03-11 15:01 UTC by sashazernin

#546

2024-03-11 16:04 UTC, hirurg-lybitel requested changes
Скинь, пожалуйста, скрин получившегося результата, потому что я не вижу никаких изменений

2024-03-11 16:40 UTC, sashazernin commented
![image](https://github.com/gsbelarus/gdmn-nxt/assets/94962537/a9c07aa9-4369-4c37-84bc-2c7f77ecbca5)

2024-03-12 14:34 UTC, hirurg-lybitel commented
> ![image](https://private-user-images.githubusercontent.com/94962537/311787093-a9c07aa9-4369-4c37-84bc-2c7f77ecbca5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNTQyOTQsIm5iZiI6MTcxMDI1Mzk5NCwicGF0aCI6Ii85NDk2MjUzNy8zMTE3ODcwOTMtYTljMDdhYTktNDM2OS00YzM3LTg0YmMtMmM3Zjc3ZWNiY2E1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDE0MzMxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0YjIwM2E5MTE4NGJmMjRkOTAwNzc0NDhlNjJjNDc3OTdmYWM0ZWFkNDIwZTI2MmMxOThkMDBkNmM4ZmExZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uw9Yo68oesYehAI5ydNlTQ8DU-kQkzvt-VooE6-GsAI)

и где тут подсветка стандартная?

2024-03-12 15:47 UTC, sashazernin commented
> > ![image](https://private-user-images.githubusercontent.com/94962537/311787093-a9c07aa9-4369-4c37-84bc-2c7f77ecbca5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNTQyOTQsIm5iZiI6MTcxMDI1Mzk5NCwicGF0aCI6Ii85NDk2MjUzNy8zMTE3ODcwOTMtYTljMDdhYTktNDM2OS00YzM3LTg0YmMtMmM3Zjc3ZWNiY2E1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDE0MzMxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0YjIwM2E5MTE4NGJmMjRkOTAwNzc0NDhlNjJjNDc3OTdmYWM0ZWFkNDIwZTI2MmMxOThkMDBkNmM4ZmExZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uw9Yo68oesYehAI5ydNlTQ8DU-kQkzvt-VooE6-GsAI)
> 
> и где тут подсветка стандартная?



> > ![image](https://private-user-images.githubusercontent.com/94962537/311787093-a9c07aa9-4369-4c37-84bc-2c7f77ecbca5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNTQyOTQsIm5iZiI6MTcxMDI1Mzk5NCwicGF0aCI6Ii85NDk2MjUzNy8zMTE3ODcwOTMtYTljMDdhYTktNDM2OS00YzM3LTg0YmMtMmM3Zjc3ZWNiY2E1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDE0MzMxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0YjIwM2E5MTE4NGJmMjRkOTAwNzc0NDhlNjJjNDc3OTdmYWM0ZWFkNDIwZTI2MmMxOThkMDBkNmM4ZmExZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uw9Yo68oesYehAI5ydNlTQ8DU-kQkzvt-VooE6-GsAI)
> 
> и где тут подсветка стандартная?

в смысле, я так понял при переключении перестается подсвечиватся кнопка настроек, я это исправл

2024-03-12 17:56 UTC, hirurg-lybitel commented
> в смысле, я так понял при переключении перестает подсвечиваться кнопка настроек, я это исправил


Ну где в задании что-то про кнопки сказано?

> Активная (текущая) вкладка не подсвечивается

У нас везде текущая вкладка подсвечивается синим цветом, а тут подветка пропала

2024-03-12 17:57 UTC, hirurg-lybitel commented
В общем ладно, тут задача на самом деле на 5 минут и пару строчек кода. Сам сделаю, а это всё удаляю

2024-03-12 17:57 UTC, closed without merging